### ISSUE TITLE
Docker documentation lacks curl nuance

### ISSUE THREAD

**Issue by tquid** [smallstep/certificates#117]
### Subject of the issue
curl doesn't automatically know the .step path certificates.

### Your environment
* OS - Ubuntu
* Version - 18.04

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo, you can use [this template](https://plnkr.co/edit/XorWgI?p=preview) as a base.

1. Try instructions given in docs/docker.md (the `curl` command after loading the ca cert)

### Expected behaviour
Should get a `{"status":"ok"}` response as documented

### Actual behaviour
curl command returns `curl: (60) SSL certificate problem: unable to get local issuer certificate
`

**Comment by tquid** [comment]
Suggested update to the doc, to go after the curl command example:

If you still get an `unable to get local issuer certificate` error, you can
add `--cacert ~/.step/certs/root_ca.crt` to the `curl` command before the url.

**Comment by tquid** [comment]
The same issue comes up with the curl command to test a local python server as well.

**Comment by maraino** [comment]
Hi @tquid, thanks for filling this issue, after reviewing the docs I think the problem is that the root certificate is not installed in your truststore. 

The `step ca command` in the [Dev environment bootstrap](https://github.com/smallstep/certificates/blob/master/docs/docker.md#dev-environment-bootstrap) section has the flag `--install` that should install the root certificate in your truststore and removes the need of adding the `--cacert ~/.step/certs/root_ca.crt`.

Can you run the command again and see if curl works for you? If not, can you run `step certificate install ~/.step/certs/root_ca.crt` and try again?

FYI: you can use `step certificate uninstall ~/.step/certs/root_ca.crt` to remove it later.

**Comment by tquid** [comment]
Well, that is embarrassing. In my frenzy to copy out the long fingerprint string, I didn't scroll quite all the way to see the `--install` option. Thanks!
