### ISSUE TITLE
[Bug]: Insecure-Option seems not to work in step-cli

### ISSUE THREAD

**Issue by IamLunchbox** [smallstep/certificates#1195]
### Steps to Reproduce

Configure a step-ca instance with an acme-provisioner. Try to get a certificate using step-cli `step ca certificate --acme-http-port=8443 --insecure  --standalone --ca-url=https://step.example.org:8443 --provisioner=acme test.example.org test.crt test.key`, get error: `flag provided but not defined: -acme-http-port`. Or use --insecure first....`flag provided but not defined: -insecure`
This feature should be available since release 0.23.0, with PR #1153 
### Your Environment

* OS - Linux with docker
* `step-ca` Version 0.23.0 (latest image)
* `step` Version 0.23.0 (Smallstep CLI/0.23.0 (linux/amd64))

### Expected Behavior

I should be able to get a certificate using port 8443 and not 80.

### Actual Behavior

Errors in step cli.

### Additional Context

I could not find documentation, if I need to tweak any step-ca settings for insecure acme http-01 challenges to work. Do I need to change the ca.json to make insecure-challenges happen?

### Contributing

Vote on this issue by adding a 👍 reaction.
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by hslatman** [comment]
Hey @IamLunchbox, the changes you link to are for the configuration in the CA. You'll need to set those flags with the ports your client is opening (if not 80 and 443). We don't support configuring those using `ca.json`, because we consider changing the port insecure. When using `step ca certificate ...`, you can use the `--http-listen :8443` flag to make it start the HTTP server for solving challenges on port 8443.

**Comment by IamLunchbox** [comment]
Hey @hslatman thank you for your fast reply. I see my error no, I misunderstood the changelog completely...and I wondered about the seemingly conflict with `http-listen` flag.
