### ISSUE TITLE
Add policy check on provisioner level

### ISSUE THREAD

**Issue by FrediWeber** [smallstep/certificates#1214]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

It would be beneficial if we could configure certificate policies on a provisioner level. It seems to me, that this feature has existed / was configurable up to this commit: https://github.com/smallstep/certificates/commit/7c541888ad281e0c6f669ce3963c0f305ac84a62#diff-3c2051c67cacc9a410bd433a329a2bf3ca926622283f9af2079b58b0eaa26aeeL61.
I don't understand why the configurability of this option was removed. Maybe this could be clarified?

## Why is this needed?

We could have multiple JWK issuers with different allowed domains on the same Smallstep instance.

**Comment by dopey** [comment]
Hey @FrediWeber 👋. Thanks for opening the issue! You are correct - we mistakenly began implementing this feature in open source even though it was intended for our paid SaaS product.

As an open core company it's been a struggle for us to figure out what belongs in open source vs. paid. Most importantly, we don't want to release crippleware ("software distributed with reduced functionality with a view to attracting payment for a fully functional version.") We believe the ability to configure to configure policy at the authority level is sufficient for most use cases. More advanced users should check out our SaaS product (https://smallstep.com/certificate-manager/).

We're always open to feedback about where and how we draw the line between paid vs open source, so definitely let us know your thoughts.

As an example of alternative models, we've tossed around the idea of having plugins to the CA, so that if you wanted to enable a specific feature you could pay for that feature only - rather than the entire SaaS product.

**Comment by FrediWeber** [comment]
Hi @dopey 
I appreciate your clarification. It would be nice to have this option as we're required to run step-ca by ourselves and we could reduce the number of necessary step-ca instances by having this policy in place on an issuer level.

**Comment by dopey** [comment]
Hey @FrediWeber I'm interested in how we could enable use cases like yours without compromising on security. I'd love to pick your brain around the requirements behind running your own PKI (e.g., where is the requirement that you run it yourself coming from - what parts specifically do you need to own). Could we set up a time to chat? My email is max@smallstep.com.
