### ISSUE TITLE
Add policy to allow any cert DNS under parent domain 

### ISSUE THREAD

**Issue by redrac** [smallstep/certificates#1260]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Right now there is a feature to only allow certain domains based on DNS of the cert IE *.foo.example.com, but that does not include *.bar.foo.example.com. 

## Why is this needed?

Many places (including our company) have complex and dynamic DNS, but have a single or a few parent domains for internal (or even external) use. I don't want to list the 100s of subdomains I do know about or account for all the unknown subdomains. It would be nice to be able to say any level of subdomain under example.com can be signed IE app.sub1.sub2.example.com.

**Comment by hslatman** [comment]
Hi @redrac,

We chose to implement this with only a single level of wildcard matching to keep reasoning about the rules simple, so that there's less room for error and surprises. Our implementation is loosely based on Name Constraints validation, but this is one of the areas it differs from it to keep the configuration (format) and evaluation simple.

It's possible to check if specific (sub)domains are allowed using the webhooks functionality. This would integrate with a system of your choice or implemented by yourself to check if the (sub)domain is in a list of allowed ones. We provide a hosted version of that in our product, which makes configuration and maintenance of that "lookup check" easy to get started with.

I'm closing this issue, given that there's a solution for this use case. It might be reopened in the future.
