### ISSUE TITLE
Serve CRL on HTTP

### ISSUE THREAD

**Issue by unreality** [smallstep/certificates#1284]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

CRL generally wants to be served over HTTP, but currently is served over HTTPS

Would it be sufficient to alter the check at https://github.com/smallstep/certificates/blob/ca9f8dc576f0cb8cb5e4aed703783533d552e62e/ca/ca.go#L307 and start the HTTP server if CRL and/or SCEP is enabled and an insecure address is configured?

**Comment by hslatman** [comment]
Yes, I think it makes sense to change the logic to also "activate" the insecure server to start if CRL is enabled. Additionally, the CRL endpoint must be mounted to the insecure server. Users of the CRL functionality should also ensure that the HTTP CRL URL is set in the issued certificates instead of the HTTPS one.

**Comment by LarsBingBong** [comment]
This would be so nice ... currently I and other as well ( see [Certificate Revocation List ](#206) ) are doing hacks to fake HTTP to get CRL CDP and IDP endpoints to work over HTTP.

Thanks

**Comment by hslatman** [comment]
I have opened a PR for this: https://github.com/smallstep/certificates/pull/1372
