### ISSUE TITLE
ACME certificates valid only 24h

### ISSUE THREAD

**Issue by pontostroy** [smallstep/certificates#131]
### Subject of the issue
Following the guide, I did my local acme server, and get certificates with cert-manager, traefik, acme.sh.
Adding claims to ca.json does not help.
```
 "authority": {
                "provisioners": [
                        {
                                "type": "jwk",
                                "name": "acme@local",
                                "claims": {
                                    "maxTLSCertDuration": "2160h",
                                    "minTLSCertDuration": "240h",
                                    "defaultTLSCertDuration": "480h"
                                },
                                "key": {


```
### Your environment
* OS - Centos 7
* Version - git master from 20191121

### Steps to reproduce
Build step-ca and setup acme server.
Get ACME certificate by acme.sh or certbot or traefik.
### Expected behaviour
The certificate must be valid for 10 days or more

### Actual behaviour
The certificate is valid only for 1 day.

**Comment by dopey** [comment]
Hey @pontostroy, based on that snippet it looks to me like you're putting the claims into a JWK provisioner (`type`: `jwk`).  I'm not sure if you've added an ACME provisioner, but if you haven't it's as easy as running `step ca provisioner add <name> --type ACME`, then restart the CA. Once you have an ACME provisioner you would add the above claims to that provisioner (instead of the JWK one). We have a [Gitter Community](https://gitter.im/smallstep/community?at=5d937d7a24509b60468f5cf8) where we help folks debug in real time. If you wanna hop in there I'd be glad to help you get things going.

**Comment by pontostroy** [comment]
from my history
step ca provisioner add acme --type ACME
and i got this json:
I move claims to acme and this solved the problem.

```
        "authority": {
                "provisioners": [
                        {
                                "type": "jwk",
                                "name": "acme@local",
                                "key": {
                                        "use": "sig",
                                        "kty": "EC",
                                        "kid": "xxx",
                                        "crv": "P-256",
                                        "alg": "ES256",
                                        "x": "xxxx",
                                        "y": "xxx"
                                },
                                "encryptedKey": "xxxxx"
                        },
                        {
                                "type": "ACME",
                                "name": "acme"
                        }
                ]
        },
```
