### ISSUE TITLE
Hashicorp Vault integration

### ISSUE THREAD

**Issue by onitake** [smallstep/certificates#138]
### What would you like to be added
A database backend for [Hashicorp Vault](https://www.vaultproject.io/)

### Why this is needed
* Secure storage of secrets
* Easy integration with existing infrastructure (when Vault is already being used for secret management)
* Vault has PKI features, but a lot less features than step-ca (ex.: no ACME server)

**Comment by mmalone** [comment]
What information would you like stored in Vault? It sounds like you want `step-ca` to issue certificates... are you wanting to use Vault's authentication mechanisms to get a certificate from `step-ca`? So when you request a certificate from Vault it's actually issued by `step-ca`?

**Comment by onitake** [comment]
Actually, I'm looking for something much simpler: I'd like step-ca to store its secure data in Vault.
Then again, I don't know what data step-ca stores in the database exactly, aside from the CA key.

**Comment by mmalone** [comment]
Oh gotcha.

To answer your question, there is no secure data stored by `step-ca` in the database. No private keys or passwords or anything like that. The private keys for JWK provisioners, used to sign bootstrap tokens, are stored in `$(step path)/config/ca.json`, but they're always encrypted (using a symmetric key / password). So there shouldn't be any concerns there.

The one thing that is a little annoying about `step-ca` is that the CA's signing key is encrypted so you need to use a password at startup. That key is stored in `$(step path)/secrets/root_ca_key`. But I'm not sure that we need to do anything there, really, since you could easily store that password in Vault and use our `--password-file` flag for a super light integration between those two components. We're also working on HSM / CloudHSM / CloudKMS support which would remove the need for a password entirely, and offer even better security.

Does this address your concerns?

**Comment by onitake** [comment]
I see, thanks for the clarification.
