### ISSUE TITLE
Feature Request: SCEP Support?

### ISSUE THREAD

**Issue by deknos** [smallstep/certificates#14]
### Subject of the issue
Hi, do you plan to support SCEP (https://tools.ietf.org/html/draft-nourse-scep-23) in your Client tool and server? I couldn't find it in your repository. It would be tremendously useful. If you support it in your client, it would help adoption and migration rate, i bet :)

**Comment by mmalone** [comment]
Do you have a specific use case or tool in mind that you’d like to integrate with? SCEP has some features that seem reasonable and others that I’m less excited to implement. It’d be a lot easier to implement the relevant subset, whatever that is.

**Comment by deknos** [comment]
Well, for one thing, SCEP is a standardized framework which is easier in an enterprise environment to accept for the auditors. Further on it makes a migration from another CA Certificate software to smallstep easier because you did not have to change the client (initially?) when you migrate from your old version away.

What are the features you do not want to implement? and why? i never encountered problems (besides old/broken implementations) with scep clients. sadly there is currently no enterprise-ready opensource scep server (and opensource enterprise ready scep client, which is multiplattform).

**Comment by mmalone** [comment]
I'd say the biggest problem here for us is a lack of familiarity with SCEP. If lots of people are using it in the enterprise I'd like to understand the use cases better, but I don't know how to do that.

I've also read a bit of the SCEP spec (er, _draft_ spec) and there are a few optional things and vague bits that I'm not sure how to implement in a vacuum. So I think the easiest thing to do would be to target a few specific pieces of existing software that use SCEP and try to work with them (e.g., take an existing client and try to be a server for it or vice versa). Do you have any suggestions re: common tools that we should look at for this? Does AD or something else really common use SCEP?

**Comment by deknos** [comment]
Well, we used for a setup OpenXPKI (server https://hub.docker.com/r/dime/openxpki/dockerfile). But it is kinda outdated because they cannot reimplement their engine on a newer version in combination with openssl. tragedy, because their templating system was really good. but that was not our main point why we used it. We used it because of the client (https://github.com/certnanny/sscep), which at that point implemented it very good in comparison to ipsec_scep-client, which... sucked. But ITSecurity and Regulations LOVE SCEP.

Implemented procedure was like that:

We rolled out clients with a initial token with which the client computers could fetch/request from a server with a certain ip in a certain timeframe a certificate for that computer. After that, the token was deleted. With that Certificate another certificate was requested/negotiated. 

the first certificate was used to reauthenticate against the PKI Server, the second one was used for 802.1x reasons.. or for system certificates or sth else.
We had a daemon which routinely checked if the certificate was half past its lifecycle and tried to update the certificates based on it.

In some instance we could generate the request ourselves, in others we had to take the management-certificate given to us by the server.

Microsoft ActiveDirectory CAN use SCEP, that was the point why we wanted to use it, because in production we couldnt go against openxpki, but against the ActiveDirectory PKI Managementserver which had an SCEP-Interface, so our linux desktop clients could authenticate against that PKI stuff.

And that would be the point, if anyone want to replace their (older) PKI stuff they often implement SCEP internally as transport/negotation protocol :)

Does my rambling make it more clear?

**Comment by alkuzad** [comment]
@deknos SCEP looks like SOAP compared to REST, abandoned by every dev on the planet and still used in outdated, legacy software :)

**Comment by dkmbw** [comment]
Well, yeah, but it is an standard used in enterprise environment. and it IS pretty robust.

**Comment by anlx-sw** [comment]
SCEP is the only way currently (afaik) to automate network device certificate management (or integrate linux servers) with a microsoft windows server certificate authority. It is named NDES there https://social.technet.microsoft.com/wiki/contents/articles/9063.active-directory-certificate-services-ad-cs-network-device-enrollment-service-ndes.aspx .

The implementation and documentation of the microsoft solution is awful in my opinion  -but it is used for some use cases frequently:
-network device certificates (e.g. for ipsec vpn) e.g. fortinet firewalls have a scep client for installation and management of ca and client certificates https://docs.fortinet.com/document/fortigate/6.2.1/cli-reference/294620/certificate-local
To request a certificate on a fortigate firewall with a pki challenge requested from the microsoft ca you can use the following command:
`exec vpn certificate local generate rsa <certlabel> 2048 <ip fortigate> null null null <companyname> null null null http://<microsoft-ca-server>/certsrv/mscep/mscep.dll <PKI Challenge> <ip fortigate>`
-mobile device management software often has a scep interface to request certificates on behave of the mobile devices and afterwards pushing the certs to the device

**Comment by mmalone** [comment]
Thanks for all the links & context folks. This is all super helpful. Please keep it coming!

In particular, please keep posting clients and servers that you're using if you're using SCEP. One of the big problems I have here is that, afaik, SCEP was never officially standardized. There are a bunch of different drafts, and I'm not sure which one to implement against. If there's a "gold standard" SCEP client that everyone uses we'd at least have a de-facto standard to work against, but that doesn't seem to exist either. Failing that, having a list of clients that people use is helpful. Ideally we need stuff that's easy for us to setup and test with, since we don't have our own existing SCEP environment.

It sounds like SCEP is used primarily in two environments:

* By network gear (I've heard Cisco stuff uses it)
* By managed endpoints (sounds like mostly in Microsoft environments)

For the latter scenario, if the endpoint is managed, why not use the `step` command-line tool instead of an SCEP client? If we had a Windows build of that tool would that solve your problem, or are there other reasons to prefer SCEP (e.g., are the clients more trusted or built-in)?

I'm also curious if the [ACME support](https://smallstep.com/blog/private-acme-server/) we just announced would work for some folks? I think informally ACME is IETF's replacement for SCEP, so it feels like the future here. I don't want to be dismissive though -- we need to operate in today's reality too. Just wondering.

**Comment by dkmbw** [comment]
There's another environment: 
Linux Appliances/Hosts/Server fetch Certificates via SCEP from Windows Certificate Server/CA/.. (automated), because it is often in a windows based environment the only possibility to get the certificates. and ACME will be not rolled out in enterprise for a long time. And ACME and SCEP serve different purposes from my POV.

Why not use step? because SCEP is a standardized protocol in enterprise environment, and there are ports open for it, and it is supported by monitoring. step communication cannot be monitored in the standard environment and has to be cleared extra by the infosec department. which hinders adoption really much.

**Comment by anlx-sw** [comment]
concerning implementation: 

i worked with a vendor a few years ago to get scep into their appliances and at that time https://tools.ietf.org/html/draft-nourse-scep-23 was used. I think most of the scep implementations are from the time when this draft was current.

I don't know if their are really any differences between the draft there and the current version https://datatracker.ietf.org/doc/draft-gutmann-scep/?include_text=1

**Comment by dkmbw** [comment]
Another thing, regarding implementation:
there is a go scep proxy (https://github.com/micromdm/scep) but this is from my POV not enterprise-grade as your product.
As client implementation for scep you could test against, there are the scep client from strongswan/openswan on linux, which in my experience is a little bit broken, but there exists also as client https://github.com/certnanny/sscep which is used in at least 2 enterprise environments.

**Comment by rmhrisk** [comment]
Microsoft's use of SCEP is highly proprietary, they have included additional proprietary meta in extensions and taken some narrow interpretations of the SCEP specification that must be teased out in testing.

While the SCEP RFC drafts are useful because of there never been a final RFC not one of those drafts reflect reliably what is needed for interoperability, at least in a broad way. 

To support SCEP you will need a list of products you want to interoperate with and build and test with those specifically in mind otherwise you will just have another SCEP implementation full of your own assumptions and not one refective of what is out there.

**Comment by dkmbw** [comment]
@rmhrisk at least sscep from keynanny/certnanny can handle  SCEP-Communication with some Microsofts SCEP implementations. if you wish i can look for the implementation versions of the AD/CA-Service

**Comment by rmhrisk** [comment]
I added the SCEP implementation to AD/CS so I am familiar. My point remains the same if you want to add SCEP you will need to know what implementations you want to interoperate with and not rely on the RFC.

**Comment by sdktr** [comment]
We’re looking into scepman, /bc scep is supported by Intunes MDM (does windows 10 as well). When there is no other user/device backend then Azure AD it is very powerfull to have any sort of PKI authenticate to this, like your OIDC provisioner does.
In this case it’s scep because the intune client on a mobile device supports that. It provides for a great silent deployment option for wireless/vpn authentication on managed devices. https://scepman.com/
To replace this an Intune provisioner and SCEP interface should both be available.

**Comment by mmalone** [comment]
This is all super useful folks. Thanks so much.

If you're reading this, haven't commented, and this is something you want **please leave some indication (e.g., give the issue a 👍) to help with prioritization**.

> To support SCEP you will need a list of products you want to interoperate with and build and test with those specifically...

This is what I was afraid of.

What I'm gathering is that there are two primary use cases:

* MDM cert enrollment integration for endpoint devices (Windows, macOS, i-devices, and even [ChromeOS](https://support.google.com/chrome/a/answer/6324985?hl=en&ref_topic=6330253) apparently)
* Enrolling network devices (primarily Cisco?)

**Please continue to leave notes on clients and existing SCEP CA implementations that you use or that you know are in use elsewhere**.

To move forward with this I think we'll have to do as @rmhrisk suggests, synthesize this feedback, and put together a list of clients that we want to support. The next step will be figuring out how to run them... I have no experience with MDM and we don't currently own a Windows machine or Cisco network gear at smallstep. So we'll have to get that all sorted out!

The reason I'm curious about existing CAs is that might be a shortcut... if all of the existing clients work with Windows Certificate Server, for instance, we could base our implementation off of theirs vs. looking at all the clients.

**Comment by anlx-sw** [comment]
yes - i think you are onto something - most commercial products will work with Windows Certificate Server NDES because of the installed base in windows ad environments.

Concerning network device enrollment:
Modern Firewalls have lots of use cases for certificates. certificate based ipsec vpn is the most prominent.

I know that two of the biggest players in this market support scep:
PaloAlto https://docs.paloaltonetworks.com/pan-os/8-0/pan-os-web-interface-help/device/device-certificate-management-scep# 
Fortinet https://docs.fortinet.com/document/fortigate/6.2.1/cli-reference/294620/certificate-local

**Comment by willglynn** [comment]
@mmalone Mikrotik RouterOS is a networking Swiss Army chainsaw, and it includes a [SCEP client and server](https://wiki.mikrotik.com/wiki/Manual:System/Certificates#Basic_SCEP_Example). RouterOS does not talk ACME, so SCEP is the best way to automatically obtain certificates on this platform. SCEP server support in `step-ca` would be useful to me for use with RouterOS clients.

Mikrotik [distributes "Cloud Hosted Router" VM images](https://mikrotik.com/download) which run on normal x86-64 hosts. There are paid licenses available, but they're not needed here:

> The free license level allows CHR to run indefinitely. It is limited to 1Mbps upload per interface. All the rest of the features provided by CHR are available without restrictions. To use this, all you have to do is download disk image file from our download page and create a virtual guest.

RouterOS can be run via [`qemu` inside Docker](https://hub.docker.com/r/evilfreelancer/docker-routeros), which might be a viable path for making a third party SCEP appliance available in development or CI.

**Comment by dkmbw** [comment]
The CertificateSoftware EJBCA and Dogtag from RedHat also support SCEP by the way (OpenXPKI (server) an Keynanny (SCEP Client) are already mentioned above). 

And there is already an prototypical implementation of scep with go: https://github.com/micromdm/scep !

**Comment by deknos** [comment]
btw, there's a new RFC in town, now. EST. testable via http://testrfc7030.com and it seems to be the successor to SCEP. But i am not aware of any client which is able to use it on linux.

**Comment by rmhrisk** [comment]
EST support in devices is very limited. It’s better designed than SCEP though.

**Comment by datduke-git** [comment]
Anyone able to get SCEP to work on iOS via Intune MDM via an apple config profile? I have it working using the GUI profile within Intune/Azure. I am trying to export/compare those values and import to an apple config profile. There is a bug with enforcing wifi via the device/mdm restrictions - the root, scep and wifi profiles do not come down together and brick the device. Trying to pull everything into one apple config profiles with multiple payloads.

**Comment by brotherdust** [comment]
> 
> 
> @mmalone Mikrotik RouterOS is a networking Swiss Army chainsaw, and it includes a [SCEP client and server](https://wiki.mikrotik.com/wiki/Manual:System/Certificates#Basic_SCEP_Example). RouterOS does not talk ACME, so SCEP is the best way to automatically obtain certificates on this platform. SCEP server support in `step-ca` would be useful to me for use with RouterOS clients.
> 
> Mikrotik [distributes "Cloud Hosted Router" VM images](https://mikrotik.com/download) which run on normal x86-64 hosts. There are paid licenses available, but they're not needed here:
> 
> > The free license level allows CHR to run indefinitely. It is limited to 1Mbps upload per interface. All the rest of the features provided by CHR are available without restrictions. To use this, all you have to do is download disk image file from our download page and create a virtual guest.
> 
> RouterOS can be run via [`qemu` inside Docker](https://hub.docker.com/r/evilfreelancer/docker-routeros), which might be a viable path for making a third party SCEP appliance available in development or CI.

Came here to mention my use-case, but @datduke-git already mentioned it. More specifically, I use it for TLS connectivity to the router's API, but it can be used for other services in RouterOS as well.

**Comment by sbingner** [comment]
https://github.com/rgorosito/ejbca/blob/master/modules/ejbca-scep-war/src/org/ejbca/ui/web/protocol/ScepServlet.java might be useful as a reference for adding this support as well.

**Comment by trs80** [comment]
I'm also interested in SCEP from the MDM (Jamf/Intune) point of view, specifically to distribute certificates for use in VPN and wireless (802.1x).

**Comment by tarelda** [comment]
@mmalone, I came across step looking for CA solution for my internal VPN needs. AFAIK, all the modern firewalls support SCEP based enrollment. While manually distributing initial certs is something I can deal with, automatic renewal is cumbersome, especially that I want to use short lived certificates. 


@sbingner, good find :)


Also I found these Cisco documents regarding SCEP:
- https://www.cisco.com/c/en/us/support/docs/security-vpn/public-key-infrastructure-pki/116167-technote-scep-00.html - brief protocol description
- https://www.cisco.com/c/en/us/support/docs/security-vpn/public-key-infrastructure-pki/211322-IOS-PKI-Deployment-Guide-Certificate-Ro.html - detailed description how SCEP is used in PKI deployment in Cisco IOS

**Comment by brotherdust** [comment]
Small step is useless to me until it has SCEP or there's a valid workaround. I'd love to use, even pay money for it!

**Comment by hslatman** [comment]
Recently I learned a bit about SCEP (and EST) and decided to implement small POCs to better understand them. I've created two Caddy modules for this: [caddy-scep](https://github.com/hslatman/caddy-scep) and [caddy-est](https://github.com/hslatman/caddy-scep). Both modules are essentially wrappers for other Go modules providing the actual SCEP and EST functionality on top of Caddy. Caddy uses Smallstep libraries under the hood to provide ACME support and I built the modules to make use of that integration. 

Currently the modules should be considered a prototype implementation. I highly doubt they are ready for production usage as is. The interfaces provided by the underlying modules [micromdm/scep](https://github.com/micromdm/scep) and [globalsign/est](https://github.com/globalsign/est) seem to work OK, but I'm also contemplating refactoring a bit to not rely on them. They may be of use to this project too.

**Comment by mkkeffeler** [comment]
SCEP would be a huge add, and super helpful in major enterprise use cases.

**Comment by hslatman** [comment]
@mkkeffeler Since my previous message I have forked this repo and started working on a bit of SCEP support. It's currently really basic because I need to learn a bit more about the code base to fit SCEP in nicely, so that's why I haven't pushed something to my fork yet. I'll probably work on it again this Friday.

My plan is to integrate parts of the POC Caddy module in a cleaner way in the Smallstep server, similar to how the ACME provisioner is implemented, and doing tests with basic CLI tools. It'll probably require a bit more time to make it work with other technologies mentioned in this issue before.

**Comment by mkkeffeler** [comment]
@hslatman good to hear, welcome to shoot me a message on the smallstep gitter or elsewhere, i have saturdays with your name on it!

**Comment by hslatman** [comment]
@mkkeffeler I've pushed some updates to my fork: https://github.com/hslatman/certificates/pull/1. It's quite rough, mostly because I'm not entirely sure how I should provide some fundamental deps to my authority and/or provisioner. A certificate can be claimed successfully with the [micromdm/scep](https://github.com/micromdm/scep) client already.

**Comment by maraino** [comment]
@hslatman Let us know if you have any question, we can also schedule a video conference with the team.

**Comment by brotherdust** [comment]
Has anyone been successful with this yet? I’ve got a smallstep CA in my home network that I’d really like to use to deploy certificates to all my IoT devices via SCEP. Having SCEP support is the last obstacle to that goal.

**Comment by hslatman** [comment]
@brotherdust: still working on it. Progress is here: https://github.com/smallstep/certificates/pull/506. You could give it a try for testing purposes :)

**Comment by brotherdust** [comment]
> @brotherdust: still working on it. Progress is here: https://github.com/smallstep/certificates/pull/506. You could give it a try for testing purposes :) 

Oh hell yes! I'll try it **today**.

**Comment by maraino** [comment]
@brotherdust It will be great if you can try it before merging it. I still have to do a last look, I've been quite busy lately, but we should merge soon.

**Comment by brotherdust** [comment]
Ok so maybe not today. Too much work. Tomorrow for funnies.

**Comment by brotherdust** [comment]
@maraino , sorry, got distracted. Trying it now...

**Comment by brotherdust** [comment]
> Hey @brotherdust which docs are down for you?

The smallstep docs. It might be me. I'll check again soon

**Comment by brotherdust** [comment]
> @brotherdust: still working on it. Progress is here: https://github.com/smallstep/certificates/pull/506. You could give it a try for testing purposes :) 

Ok. So I got the referenced pull request compiled. It's not all that clear to me how to enable SCEP. The pull request says it works with micromdm, so I assume there must be some kind of integration happening here? Sorry, I'm used to how SCEP and NDES works with Windows CA.

**Comment by brotherdust** [comment]
@dopey , just so you know, it looks like the docs are unavailable via IPv6. I turned off IPv6 and I can access them now.
`smallstep.com` resolves to `2604:a880:400:d0::1741:7001` and `2600:1f18:2489:8201:aeea:87a5:6524:10fd`, both of which are pingable but don't seem to want to respond to my request.

**Comment by maraino** [comment]
@brotherdust @dopey I've just disabled IPv4 and it's working fine for me on IPv6. And without messing up with your network you can also test it with:
```
curl -k -H 'Host: smallstep.com' https://\[2604:a880:2:d0::2103:a001\]
```

**Comment by maraino** [comment]
@brotherdust It resolves for me to different IPs for me:
```
$ dig AAAA smallstep.com
...
smallstep.com.		1	IN	AAAA	2600:1f1c:471:9d00:64a9:5908:2245:64e0
smallstep.com.		1	IN	AAAA	2604:a880:2:d0::2082:a001
```

**Comment by brotherdust** [comment]
@maraino , don't sweat it. I can access it via IPv4 so I'm good. It's probably me. I have lots of weird network settings due to all the labs I run.

**Comment by hslatman** [comment]
@brotherdust: regarding micromdm; that's one of the SCEP client implementations that I used to test. There's no hard requirement to use it for your tests. 

Some instructions for getting step to serve SCEP are in the PR, but they may have been hidden for you: https://github.com/smallstep/certificates/pull/506#issuecomment-798987601. You'll need to ensure to run step with RSA keys, because that's what's currently supported and in the SCEP RFC. You'll have to adapt your client to make use of the SCEP provisioner that you configure. 

Let me know if you hit a blocker.

**Comment by hslatman** [comment]
And then I saw your edit 😅

**Comment by hslatman** [comment]
@maraino: note that I have (at least partly) addressed those issues in my most recent commits.

**Comment by maraino** [comment]
Initial SCEP support has been merged to master. Thanks @hslatman 
https://github.com/smallstep/certificates/pull/506

**Comment by deknos** [comment]
atm i do not see any documentation for scep? will there be a tutorial? @maraino @hslatman ?

**Comment by hslatman** [comment]
Hi @deknos,

I will discuss this with @maraino and the rest of the step team.

In the meantime you can have a look at [this comment](https://github.com/smallstep/certificates/pull/506#issuecomment-798987601) on the PR. It's the setup that I used to implement and test the implementation with some SCEP clients. You'll probably need to adapt it to your setup. The other comments in the PR may also give you some hints as to how to configure SCEP.

Note that SCEP clients may expect certain behavior from a CA which may not have been implemented as such in step at this time. Let me know if you find issues.

**Comment by brotherdust** [comment]
Ok. I finally got step-ca into production and working. I'm going to try SCEP shortly.

**Comment by koalo** [comment]
@hslatman Since you implemented caddy-est as well, are there plans to integrate EST into Smallstep as well?

**Comment by hslatman** [comment]
Hi @koalo, it has come up a few times, but the last time it was asked for by someone from the community and/or customers that I'm aware of is pretty long ago. I'm still interested in the protocol and integrating it, but it makes less sense business wise and from a maintenance viewpoint, as there are simply not as many users/systems using the protocol; at least as far as I know. I can see it being another avenue for systems currently using EST to migrate over to ACME (DA) for cryptographically attested device identity if we supported EST. 

Let me know if you have further questions and/or are looking for a solution that's suitable for embedded systems.

**Comment by hslatman** [comment]
> [@hslatman](https://github.com/hslatman) Thanks for the quick response!
> 
> > are looking for a solution that's suitable for embedded systems.
> 
> Yes, that is exactly what we are looking for! Essentially just how to get proper TLS certificates for a webinterface onto embedded devices from network routers to industrial robots.
> 
> The performance or complexity is not really the point (since we are usually building upon Linux for embedded systems), but conventional ACME seems to me not really suitable (at least in my understanding, please correct me!) in many environments of embedded systems where the device identity is often not coupled with the hostname or IP address of the device e.g. its just distributed via DHCP.

If you want to use the TLS certificate for a web interface, then including a hostname or IP address in the certificate _does_ make sense, and in the case "conventional ACME" would be a good fit. But in this case you probably want multiple ACME identifiers: a hostname and/or IP, _and_ an identifier that uniquely identifies the device (e.g. a serial, or the like). When an ACME client submits such a request it would have to solve different challenges based on the identifier type, and only after all challenges are validated successfully, will a certificate be issued. In your final certificate you would have a hostname and/or IP _and_ the additional device identifier. This option requires the devices to be able to access the ACME server; there are other ways to do it too, of course.

> Likely, the biggest challenge is "what else, if not the hostname or IP address, identifies an embedded device in a suitable way, so that the user can be confident that a specific device is really the one he is currently communicating with during onboarding?". There are numerous approaches, including "I trust the one that responds first to a fixed initial IP address" (hopefully in a trusted onboarding network...). The more secure ones we have some experience with include techniques like FIDO device onboarding and OAuth device code grants.

This is a good point, indeed, and likely needs a discussion on the hardware on and capabilities of the devices you're working with. Some form of trusted hardware, like a TPM, would be great. I believe FIDO Device Onboarding does include some way for a TPM to be involved too. 

> But after the initial trust is established, we still need a proper way to install the TLS certificates. I implemented some hand-made protocol in the past, but would prefer a more standardized way. SCEP might be possible, EST sounded just a little better, but I have never heard about ACME DA before.
> 
> I read your very interesting blog article about it ( https://smallstep.com/blog/managed-device-attestation/ ) and you convinced me with your statement "By building on the well-defined and extendable ACME protocol, instead of retrofitting TPM attestation to older protocols supported by MDM solutions" to further look into that, even though "It doesn’t specify how a device attests its identity in the first place, or how the attested identity has to be verified by an ACME server."

In our platform we check for specific device identifier types based on the platform the attestation comes from, and compare that to a known good value. For example for devices that have a TPM we check the TPM EK to be known, and issue a certificate to an attestation key (the first part). That certificate is then sent with the request for a certificate using ACME DA to proof that the key was created by a device with a TPM that enrolled into the platform successfully before (the second part).

> If you are interested, I would be very happy to discuss this further and to get pointers how the latter aspect could be handled in our scenario!

Assuming you're willing to discuss a commercial solution, the contact form on our website is the best place to put your information. I'll likely see it coming in, and can add some context to your contact details. Otherwise our Discord would be a good place to discuss your use case more.

> By the way: The contact link at your blog post leads to a 404.

Thanks! I've created a ticket to fix this.

> By the way 2: draft-acme-device-attest-03 is no longer active. Are you aware what the future plans are about it?

The usage of the standard is already implemented in macOS and iOS with the [ACMECertificate](https://developer.apple.com/documentation/devicemanagement/acmecertificate) payload, and several MDMs have implemented support for that profile. It's mostly a matter of finishing it up, but there's a lot of things we're working on, so it's not always top of mind. I'll try to see if we can move this forward more actively ourselves.

**Comment by koalo** [comment]
@hslatman Thanks!

> If you want to use the TLS certificate for a web interface, then including a hostname or IP address in the certificate _does_ make sense, and in that case "conventional ACME" would be a good fit. But in this case you probably want multiple ACME identifiers: a hostname and/or IP, _and_ an identifier that uniquely identifies the device (e.g. a serial, or the like). When an ACME client submits such a request it would have to solve different challenges based on the identifier type, and only after all challenges are validated successfully, will a certificate be issued. In your final certificate you would have a hostname and/or IP _and_ the additional device identifier. The resulting certificate can then be used for the web interface (it has the correct hostname/IP), as well as a client certificate to authenticate to other systems. This option requires the devices to be able to access the ACME server; there are other ways to do it too, of course, and we can support such use cases in `step-ca` or in our platform.

Yes, that is a very good point! We likely need both at the same time to only issue certificates to allowed devices (via DA challenge), but also make sure they are only issued for the correct hostname/IP ("classical" challenge).


> This is a good point, indeed, and likely needs a discussion on the hardware on and capabilities of the devices you're working with. Some form of trusted hardware, like a TPM, would be great. I believe FIDO Device Onboarding does include some way for a TPM to be involved too.

AFAIK a TPM is not strictly required for FIDO Device Onboarding, but IMHO it only really makes sense when having one.
We generally assume we have a TPM (or equivalent like a Secure Enclave on the SoC) also for fulfilling a whole bunch of other security requirements (e.g. IEC 62443 at least SL-3 and 4 explicitly asks for hardware security for authenticators, but also for SL-2 it is much more difficult without).

> In our platform we check for specific device identifier types based on the platform the attestation comes from, and compare that to a known good value. For example for devices that have a TPM we check the TPM EK to be known, and issue a certificate to an attestation key (the first part). That certificate is then sent with the request for a certificate using ACME DA to proof that the key was created by a device with a TPM that enrolled into the platform successfully before (the second part).

I guess the "check the TPM EK to be known" is the most interesting part here, i.e. how your system knows which EKs it should "know".

> Assuming you're willing to discuss a commercial solution, the contact form on our website is the best place to put your information. I'll likely see it coming in, and can add some context to your contact details. Otherwise our Discord would be a good place to discuss your use case more.

Thanks! I will contact you via the form to provide more background and then we can still switch elsewhere (e.g. Discord) if we want to get a broader involvement of others.

> > By the way 2: draft-acme-device-attest-03 is no longer active. Are you aware what the future plans are about it?
> 
> The usage of the standard is already implemented in macOS and iOS with the [ACMECertificate](https://developer.apple.com/documentation/devicemanagement/acmecertificate) payload, and several MDMs have implemented support for that profile. It's mostly a matter of finishing it up, but there's a lot of things we're working on, so it's not always top of mind. I'll try to see if we can move this forward more actively ourselves.

I will be at IETF 123 in Madrid at least on Friday. Maybe I can also find someone to poke there ;-)

**Comment by hslatman** [comment]
Hey @koalo, 

I just saw https://github.com/smallstep/certificates/issues/2366 pop up, so you could follow that if you're still interested in EST too 🙂 

Did you get hold of someone at IETF 123? I know Brandon presented remotely and gave a quick update on the device attest RFC, with the main points being some more adoption and referencing the new attestation format, eventually replacing the formats "borrowed" from WebAuthn.

**Comment by koalo** [comment]
> I just saw https://github.com/smallstep/certificates/issues/2366 pop up, so you could follow that if you're still interested in EST too 🙂

Thanks for the hint! But you convinced me that using ACME in one of its flavours (or even a new one if other requirements might emerge) would be better than SCEP or EST (unless for legacy applications) 🙂

> Did you get hold of someone at IETF 123?

No. Since Brandon has published and presented a new version of the draft, it is obviously still on track, so I have not seen any worth in poking others 🙂
