### ISSUE TITLE
Use an environment variable for the password instead of `--password-file`

### ISSUE THREAD

**Issue by CMCDragonkai** [smallstep/certificates#154]
### What would you like to be added

Right now to automate the password deployment of `step-ca` I have to use `--password-file`, otherwise multiple files will be asking for the same password.

Instead we could use an environment variable that achieves the same thing. It would avoid polluting the CLI history as well, and avoid the need to always create a pseudo file for my password.

### Why this is needed

There's no real loss in security. This is only intended for automated deployment.

**Comment by dcow** [comment]
How are you running the CA on the host? `systemd`?

**Comment by CMCDragonkai** [comment]
I'm putting the CA inside the container, and then running that container in ECS.

**Comment by CMCDragonkai** [comment]
Would be great if this was available to the `step certificate create` command as well. That isn't automatable atm.

**Comment by dopey** [comment]
The research that we did here a few years ago was that passing secrets in the environment was unsafe, or else, no more safe than using a file. If anyone would like to argue in favor of using environment variables for passwords (from a security standpoint) we're happy to listen and have our minds changed. Otherwise this is something we won't be prioritizing.

**Comment by CMCDragonkai** [comment]
Both the filesystem and environment variables are part of the ambient authority. They are equivalent in security but just convenient in different ways.

On 29 April 2020 06:47:46 GMT+10:00, Max <notifications@github.com> wrote:
>The research that we did here a few years ago was that passing secrets
>in the environment was unsafe, or else, no more safe than using a file.
>If anyone would like to argue in favor of using environment variables
>for passwords (from a security standpoint) we're happy to listen and
>have our minds changed. Otherwise this is something we won't be
>prioritizing.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/smallstep/certificates/issues/154#issuecomment-620846081

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dcow** [comment]
Specifically, `systemd` discourages using the environment because it doesn't consider them secure and exposes them over dbus:

> Note that environment variables are not suitable for passing secrets (such as passwords, key material, …) to service processes. Environment variables set for a unit are exposed to unprivileged clients via D-Bus IPC, and generally not understood as being data that requires protection. Moreover, environment variables are propagated down the process tree, including across security boundaries (such as setuid/setgid executables), and hence might leak to processes that should not have access to the secret data.

For container, namespace, and/or non-systemd scenarios I could see an argument for the convenience. But only using the option in those cases would need to be drilled into users, and we generally don't like software that lets users stumble upon insecure patterns. 

I don't think it's been mentioned in this thread yet, and for posterity, if you've secured your environment and rely on it for secrets:

    step-ca --password-file <(echo -n $STEP_CA_PASSWORD)

**Comment by dopey** [comment]
We've added an FAQ to the cli repo with an answer to this question (cribbed from @dcow's response above). 

I'm going to close this issue for the time being, but please feel free to leave a comment if you'd like us to re-open for further discussion. Or open an issue on the CLI repo citing the documentation that you'd like to discuss.

**Comment by bbrendon** [comment]
anyone know how to do pipe the password from the environment on windows?

```
PS C:\Windows\TEMP\step-uncompress> write-output "asdf" | step ca certificate user client.crt client.key 
✔ Provisioner: support@domain.com (JWK) [kid: 6Ablw3Duj0lrshEoZxmQC-0aKxNS-zn_iu7-zFK2pBE]
                                                                                                                                        
error reading password: ^D
```
