### ISSUE TITLE
[Bug]: Multiple ACME certificate reloading fails when using a smartcard

### ISSUE THREAD

**Issue by Sani7** [smallstep/certificates#1548]
### Steps to Reproduce

Create a Caddy web server with step-ca as an ACME Certificate Auth with Yubikey with a certificate in the 9c slot.
Create multiple reverse proxies or webpages, ... using that CA.

### Your Environment

* OS - Fedora 38 Amd64
* `step-ca` Version - Smallstep CA/0.24.2 (Linux/amd64)

### Expected Behavior

Each request gets queued and gets handled asynchronously every time the Yubikey is available and gets a new certificate.

### Actual Behavior

Each request gets queued and handled asynchronously, but the smartcard can't handle Certificate Signing Requests asynchronously and returns an error code. So none of the servers get a new certificate. Step-ca returns a 500 internal server error to each of the requests. This is the internal error in the system log from step-ca:
`error creating certificate: error creating certificate: command failed: smart card error 6a80: incorrect parameter in command data field" fields`

### Contributing

Vote on this issue by adding a 👍 reaction.
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by hslatman** [comment]
Hi @Sani7, thank you for opening the issue.

The problem you describe sounds somewhat similar/related to what's described in https://github.com/smallstep/certificates/issues/1463. The fix for that was implemented with https://github.com/smallstep/certificates/pull/1476, but that hasn't landed in a release yet. Could you try [one of the RCs](https://github.com/smallstep/certificates/releases) for the upcoming release to see if the problem still occurs with one of those? 

We're going to release a new version of the CA soon, so if you can't try the RC, you can test it with the official one soon.

**Comment by hslatman** [comment]
I saw you closed the issue, @Sani7. Did the RC fix it for you? Our latest release is out now too, so if the RC worked, you can use that too: https://github.com/smallstep/certificates/releases/tag/v0.25.0.

**Comment by Sani7** [comment]
I first used RC5, which worked. Then switched to v0.25.0 and that still worked fine.

**Comment by hslatman** [comment]
Great 😄
