### ISSUE TITLE
Open device-attest-01 support

### ISSUE THREAD

**Issue by benlongo** [smallstep/certificates#1707]
## Hello!
- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

>  There is no support for device-attest-01 TPM certificate flows in our open source packages.

https://github.com/smallstep/certificates/discussions/1545

## Why is this needed?

There are many applications for device-attest-01 beyond just enterprise MDM, and it's a shame the implementation isn't open source.

**Comment by hslatman** [comment]
Hi @benlongo, what exactly are you looking for? 

Our implementation of `device-attest-01` does in fact support the `tpm` format. Our CLI has very basic support for it too. Our `crypto` package has several parts related to supporting TPMs. The part that's not in `step-ca` is the attestation CA, but in terms of responsibilities and implementation scope, that part is supposed to be in an independent/different system, IMO. Then, after the attestation CA does its job, `step-ca` can authorize an ACME request using the `tpm` format.

**Comment by benlongo** [comment]
Hi @hslatman, thanks for your response. I believe I have misinterpreted the contents of #1545 which to me seemed to suggest that a critical component was missing to implement `device-attest-01`, but after reading more carefully it appears my understand of the protocol was flawed and I was conflating the attestation CA with step-ca.

**Comment by glance-** [comment]
I'd be happy with a simple example attestation CA service code and some documentation/examples that shows what the flow actually would be.

When I played around with this it was all way to opaque for me to be able to figure out what bits go where.

**Comment by hslatman** [comment]
@benlongo No problem 🙂 I have to admit that the `tpm` format and how to use it with `step-ca` is currently not that well explained, so I understand where you're coming from.

@glance- I'll see what I can do. It'll probably be documentation based first.

**Comment by eamontaf** [comment]
@hslatman  We are also interested in documentation around using the device-attest-01 flow with TPMs, so any documentation you can provide would be much appreciated.

**Comment by benlongo** [comment]
@tashian I'm interpreting your message as an indication that smallstep does _not_ plan on making the TPM2 attestation workflows available in their open source packages. This seems to be contrary to @hslatman's previous comment suggested that this was indeed part of the open source offering. 

I would be very disappointed if this is the case, but understand the business case for it. If you do not plan on open sourcing `device-attest-01` support, then please close the issue.

**Comment by tashian** [comment]
Hi @benlongo, thanks for the feedback. I admit it's tricky to find a balance because I want people to know that we have commercial options that may be a better fit for them, but I'm not here to pollute the conversation with ads.

And I think you may have read a bit too much into my note, so I should clarify.

My understanding of this issue is that we already have device attestation features in open source—some added very recently—that are not very well documented. Our docs contain approximately one paragraph about `device-attest-01.` So, I think there’s more we could do and am discussing with Herman where the gaps are. Personally, I'd like to see a [YubiKey example](https://smallstep.com/blog/access-your-homelab-anywhere/) at minimum. I've opened smallstep/docs#321 to cover this part.

In the meantime, beyond our current docs, we have the following blog posts about device attestation, which might help you:
- [Managed Device Attestation: ACME as the Bottom Turtle in Mobile Device Management](https://smallstep.com/blog/managed-device-attestation/)
- [Managed Device Attestation Explained](https://smallstep.com/blog/acme-managed-device-attestation-explained/)

Now, on to the meat of the issue. It's true that we have no plans to release an open source TPM attestation CA, and if that's what this issue is really about, then we should close it.

However, I understood the issue to be a bit more broad.  step-ca` has always been focused on DevOps use cases. The value of this issue is that it advocates for "applications for `device-attest-01` beyond just enterprise MDM" — TPM or otherwise — and that's something we should continue to explore. And that's the case for keeping it open, so people can voice their support and help shape future developments.

So, while our focus on DevOps for `step-ca` doesn't _preclude_ further device attestation features, it does mean we need to serve the greatest need for DevOps first. And that need is for workload identity certificates, not device certs.

Finally, I want to say with humility that this is a sensitive topic for us right now. We are 5 years into the development of `step-ca`, yet the philosophical boundaries of this project are still emerging—especially the boundaries between open source and commercial. These boundaries are critical for choosing what is out of scope. We do not want this project to be burdened by unrelated or niche features that are not serving its core use cases. I would say that's been a huge risk for open source projects in the past, and it's one we'd like to avoid.

**Comment by benlongo** [comment]
@tashian thanks for the response - I do understand the difficulty in defining the boundaries both in broader scope, and where to split the line between commercial and open source. I also admit my understanding of the various pieces of the `device-attest-01` protocol is limited and I haven't looked at it in awhile. 

Perhaps it would be useful to explain my use case that ultimately motivated creating this issue because I think it is much more aligned with the scope of DevOps than MDM which feels more 'IT'. Our team has a large number of servers deployed at remote locations. These devices ultimately need to authenticate with AWS workloads. AWS offers IAM Roles Anywhere, and y'all even have an excellent blog post illustrating how to use this with step-ca: <https://smallstep.com/blog/smallstep-and-aws-iam-roles-anywhere/>. My ultimate goal is to utilize the TPM2 on these servers with `device-attest-01` to get IAM Roles Anywhere certificates onto these servers. 

From my perspective, this is definitely in the scope of DevOps, although it does share almost identical technical structure to the MDM use case.

**Comment by tashian** [comment]
Thanks for articulating your use case, Ben. And I agree that it's a solid DevOps use case.

There are several TPM certificate workflows possible with `device-attest-01`. I have spent a lof of time researching TPM 2.0 and the TCG specs, and I still feel like a beginner when it comes to understanding the certificate workflows and their use cases. Several workflows are specified but few, if any, have been adopted or implemented in open source.

However, I'm almost certain that you would need an Attestation CA in order to have an _attested_ device identifier on a certificate for your desired use case. The Attestation CA is beyond the scope of `step-ca`. It's not simply a missing provisioner type; it's a separate component that should be developed as an independent project.

So, I'm going to close this issue. Circling back to what @hslatman [said earlier](https://github.com/smallstep/certificates/issues/1707#issuecomment-1932649041), `step-ca` fully supports the `tpm` attestation format. From my POV, `step-ca` has done its part here by implementing ACME `device-attest-01` to spec on the server side.

If someone wants to build an open source Attestation CA for TPM2, it would certainly unlock more use cases.

**Comment by andsens** [comment]
> However, I'm almost certain that you would need an Attestation CA in order to have an attested device identifier on a certificate for your desired use case. The Attestation CA is beyond the scope of step-ca. It's not simply a missing provisioner type; it's a separate component that should be developed as an independent project.

If I am not mistaken, something like Googles [go-attestation](https://github.com/google/go-attestation) library could fill that gap, correct?

**Comment by hslatman** [comment]
> If I am not mistaken, something like Googles [go-attestation](https://github.com/google/go-attestation) library could fill that gap, correct?

Absolutely, but `go-attestation` only provides you the lower level bits; not the client <-> server (attestation CA) interaction/protocol, so that would still have to be implemented.

We rely on [go-attestation](https://github.com/smallstep/go-attestation) (our fork, until all our changes are upstreamed) ourselves in e.g. our [tpm](https://github.com/smallstep/crypto/tree/master/tpm) and (more specifically) the [attestation](https://github.com/smallstep/crypto/tree/master/tpm/attestation) packages. In `step-ca`, it's used as part of the ACME challenge validation: https://github.com/smallstep/certificates/blob/master/acme/challenge.go#L666-L679.

**Comment by Foxboron** [comment]
I've started an FOSS implementation of the attestation server here.

Please note it's all POC/WIP, it will accept anything shaped like a TPM at the moment, but I intend to run this as a personal thing and we'll see how complete it becomes.

https://github.com/Foxboron/attezt

**Comment by andsens** [comment]
@Foxboron awesome! I'll be keeping a close eye on that :-)

**Comment by salrashid123** [comment]
if interested for reference, i spend a number of hours looking at the [specs](https://datatracker.ietf.org/doc/draft-ietf-acme-device-attest/) and reverse engineering the csr/cert specs smallstep-ca

https://github.com/salrashid123/device-attest-01

i'm pretty sure i've missed  deep details but it does do standard TPM remote attestation to get an AK and processes the challenge with step-ca which does issue the cert... the intent for thta repo is mostly just to 'see' it work by hand

**Comment by hslatman** [comment]
Hey @salrashid123,

Already saw you push that up! I'll definitely give it a look when I get some time.

Btw, thank you for all the other Go TPM examples. I've taken many a look over the course of the past years while working on our own TPM stuff to learn from them 😄
