### ISSUE TITLE
[Docs]: Additional information about the database schema (MySQL) + data in plaintext instead of blobs

### ISSUE THREAD

**Issue by jojof2024** [smallstep/certificates#1771]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to document this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Affected area/feature

Is there any additional about the step ca database schema (espacially for MySQL)? What is saved in which tabels? Where do I find what information? And is there a possibility to save the data in the step ca database as plaintext instead of blobs? 

E.g. where can I find the status and other information about the issued certificates? Is there a possibility to pull a report of all issued certificates in plaintext? Or is there a possibility in general to pull a report of all data in plaintext?

**Comment by tashian** [comment]
Hi there.

We use blobs because they are compatible across all of the types of databases that we support, including key-value stores like BadgerDB. Unfortunately, we don't have the capacity to document the database schema anytime soon.

An alternative is to parse the step-ca logs (which you can configure to emit in json), as they will contain the contents of every certificate issued.

Or, our [commercial CA](https://smallstep.com/product/) offers searchable logs of issued certificates in the UI or [via an API call](https://gateway.smallstep.com/operations/ListCertificates).
