### ISSUE TITLE
External Log/Event providers.

### ISSUE THREAD

**Issue by Johannestegner** [smallstep/certificates#184]
### What would you like to be added

Ability to configure multiple loggers (active for specific levels).  

Logrus (which is the underlying logging framework) seems to have decent functionality for hooks to send logs to other providers such as logstash and similar.  
Adding a couple of those and expose configuration for the providers implemented would be very helpful.

### Why this is needed

Monitoring the PKI manually is a burden, being able to use a logging and event handling tool that is already in use by the organization or person hosting the PKI would make it a lot easier.

**Comment by dopey** [comment]
First off, this is definitely something that should be added. Allowing users to hook in their own providers is a great idea.

I'd be curious to know if you had specific use cases in mind. 

The reason I ask is because, as you said, monitoring PKI is hard. Internally, we've been thinking that a Certificate Transparency Log integration would be the best tool for the job (which will be a large project and orthogonal to logging as we do it today). 

Back to this issue - unfortunately we won't have time to implement this short term. If we see more support for extending the logging infrastructure as you described then we'd be happy to adjust our short to midterm roadmap. In the mean time, we're happy to take PRs and we be happy to work with you (or anyone else interested in picking this up) to get this feature merged.

**Comment by Johannestegner** [comment]
Use-cases that I have thought about is to push logs to external providers like logstash or just plain 'ol syslog (with syslog you can always forward logs if wanted, which makes it quite a good first step, hehe).
When it comes to events, I use Sentry a bit for other services, pushing events such as certificate failures, maybe even authentication failures and other "high priority" issues would be great.

I will surely see if I can figure out a good way to help implement this, will let you know if I come up with a decent solution! :)

---

The way I currently handle my step-ca logs is like this:

I use a Ubuntu 18.04 server as the host for my step-ca instance. The server have a systemd service script for step-ca which takes care of starting, restarting and stopping the service. Through systemd, all logs go to the journald service, which is possible to forward to rsyslog!
In Rsyslog I have configured all logs with the $programname `step-ca` to forward to my logz.io instance.

It works okay, a bit of a... routing nightmare maybe! but still _okay_, hehe.

**Comment by mmalone** [comment]
@Johannestegner thanks for the feedback. When we built `step-ca` it was an intentional choice to have it start in the foreground (_not_ daemonize) and write logs to `stdout` (_not_ directly integrate with any particular log aggregation system(s)). We figured that would offer the most flexibility for folks to handle supervision and log aggregation however they'd like in Linux userspace (e.g., using `systemd` and forwarding to rsyslog, as you've mentioned).

I'm not an expert on the pros & cons of all of the permutations of setups to complete these tasks. What's the advantage of having the software write directly to some aggregation system vs aggregating from stdout? If we're saving our users a ton of time, we'll consider it. But I'm afraid we'll always be chasing integrations here, and the mechanisms for aggregating from stdout are probably way more mature than our integrations will ever be.

**Comment by Johannestegner** [comment]
@mmalone I very much understand how you think and I also think that it's a good idea to try keep the connectors out of the codebase. I'll see if I can figure out the best way to handle the whole flow and post something about it when I have done that. Thank you for the response!

(It's okay to close the issue if you wish). :)

**Comment by dopey** [comment]
Cool, gonna close this issue for now, but happy to have it opened up for more discussion in the future.
