### ISSUE TITLE
Sign and sha binaries.

### ISSUE THREAD

**Issue by Johannestegner** [smallstep/certificates#191]
### What would you like to be added

Would love to see an extra step added to the build pipeline in which the produced binaries (well, all files in the releases) are signed with PGP and a SHA hash so that it is easier to verify the files when downloading from github.

### Why this is needed

Security is awesome, and with PKI security is highly important. Being able to verify the server binaries when downloading would be a nice thing!

**Comment by mmalone** [comment]
How would you obtain the PGP public key / expected hashes required to verify the signature / hash? Does GitHub host those artifacts? Do you know of any projects that do this well, so we can look at what they're doing?

**Comment by Johannestegner** [comment]
Well, the public key could be posted in the readme basically (if many, you could post the keys of each person with the right to sign). The SHA could be uploaded with the other files.
Often, the specific binaries are not signed, only the checksum files.

When I do it for my own binaries, I do it like this:

1. Build binaries.
2. Create a checksum with sha256sum.
3. PGP/GPG sign the sha256sum.

The public key of that signs the sha256sum is published on most of the pgp keyservers and posted in the readme as the sign-key.

This way, the only trust issue is that the pgp key is valid. As long as it is, and the shasum is verified with a pgp check and the sums verify that the binaries are correct, everything is fine.

If you want, I can take a look at at the least creating a shasum file in the `make` file (which if added there would not force you to add extra steps to the build procedure). The pgp part I could add, but it might be a bit annoying when publishing if you guys don't want it, so I'll do that in another PR in that case ;)

When it comes to other projects:

Node.js post their release keys in their README in the repo:
https://github.com/nodejs/node#release-keys

They also have a short part in their readme about verifying the releases:  
https://github.com/nodejs/node#verifying-binaries

They sign the sha file, the sha file then verifies the actual binaries.

**Comment by dcow** [comment]
I'm not a pgp hater, but you are still trusting WebPKI (and github.com, not smallstep) to deliver you the correct shas. What signing artifacts really does, in my opinion, is allow you to distribute them so they can be served by people/hosts/entities _other_ than the original authors/builders (relayed by 3rd parties). This is why debian (and derivatives) relies heavily on pgp, they have (or had) a strong mirroring culture. You'll also notice debs are not served over `https`. They don't need to be because it doesn't matter if somebody intercepts the deb, they can't break the signature. The keys are seeded with your distribution so debian has built its own distribution PKI on top of PGP instead of TLS. 

Anyway, my point is that in lieu of a way for us to communicate a pgp key securely that doesn't bootstrap off of TLS, I don't strictly see an immediate security advantage. As a nerd, I have no issue signing things with PGP and definitely appreciate it when the software I download provides me a way to verify its integrity regardless of whether I received the data via web-pki or otherwise. And it would be nice to not have to worry about people repackaging our stuff. Perhaps we should set up a https://packagecloud.io/ apt repo and start hosting our linux distributions there?

**Comment by Johannestegner** [comment]
@dcow , yes, you are correct, it is not a fool-proof solution, but as it is now we only trust the github login of the authors/publishers. If anyone of them would ever be compromised (even a single API key), that would mean that the chain of trust is broken.
If the PGP key was published on the smallstep website or even in the repo (so that people could look at the history of the keys), we would at the least have one extra step of validation.
I very much understand your thoughts, and I would never think that this would make it 100% safe, but it would at least add one extra step. A step that is commonly used in distribution of software.

When it comes to packagecloud, they basically do it this way, and if you have the funds for it, I would very much like it (as it just requires a small change to the .deb files, and would allow updating the packages via apt or other pkg managers!). :)

---

I will gladly invite you to my next key signing party (if I ever host one! And no, I have not yet... :P ) :D

**Comment by dcow** [comment]
Awesome sounds like we're pretty much all on the same page. We'd certainly welcome any work you've sketched out to kick us off in that direction. Full thought out linux distribution will likely require some discussions on our side but I'd say it's something we are interested in buffing up.
---
Happy to attend any signing parties! Specifically I meant finding a `debian` maintainer and getting us into the distributions, which generally requires/implies a face-to-face key exchange.

**Comment by dopey** [comment]
With the release of v0.17.2 we are using [cosign](github.com/sigstore/cosign) to sign over all artifacts produced by goreleaser and uploaded to the release page as part of the build process. Let us know if there are particular artifacts that are still missing signatures that you'd like to see.
