### ISSUE TITLE
Subject name is re-encoded upon signing with default or custom templates

### ISSUE THREAD

**Issue by Drsmite** [smallstep/certificates#1917]
I'm attempting to resolve an issue with RedHat IPA.  The product requires the subject on the certificate to be encoded a certain way (UTF8String)
https://www.freeipa.org/page/Troubleshooting/PKI#external-ca-renewal-with-ipa-cacert-manage-fails
I have tried to accomplish this through templating by trying:
"subject": {{ toJson .Insecure.CR.Subject }}
"subject": {{ asn1Marshal .Insecure.CR.Subject "utf8" | toJson }} (and various permutations but I just get what looks like Base64 as the subjectName
Using a wide open template of {{ toJson .Insecure.CR }} the subject is correct.  However, the AuthorityKey is incorrect because the CSR IPA generates contains identical Subject Key Identifier, and Authority Key Identifier (so when it looks self signed).
I've attached a sample CSR.
ca-asis.crt was signed using the '{{ toJson .Insecure.CR }}' template
ca-template.crt was signed using '"subject": {{ toJson .Insecure.CR.Subject }}...'

[ca-template.crt.txt](https://github.com/user-attachments/files/16131550/ca-template.crt.txt)
[ca-asis.crt.txt](https://github.com/user-attachments/files/16131551/ca-asis.crt.txt)
[ca.csr.txt](https://github.com/user-attachments/files/16131553/ca.csr.txt)

**Comment by maraino** [comment]
Hi @Drsmite, the subject `O=NAVITAIRE.COM,CN=Certificate Authority` doesn't have any character that is different in ASCII an UTF-8, so I don't see the problem in your examples. 

I can create a CSR with the subject in UTF-8 and sign it without issues:
```console
$ step certificate create --csr --san example.com "Thïs shóúld be ü†F8™" csr.crt csr.key
Please enter the password to encrypt the private key:
Your certificate signing request has been saved in csr.crt.
Your private key has been saved in csr.key.
$ step certificate sign  --profile leaf csr.crt ~/.step/certs/intermediate_ca.crt ~/.step/secrets/intermediate_ca_key
Please enter the password to decrypt /Users/mariano/.step/secrets/intermediate_ca_key:
-----BEGIN CERTIFICATE-----
MIIB1TCCAXugAwIBAgIRANgTQ8QQNEg4z+plNs9nZTYwCgYIKoZIzj0EAwIwJDEi
MCAGA1UEAxMZU21hbGxzdGVwIEludGVybWVkaWF0ZSBDQTAeFw0yNDA3MDkxOTIz
MTdaFw0yNDA3MTAxOTIzMTdaMCcxJTAjBgNVBAMMHFRow69zIHNow7PDumxkIGJl
IMO84oCgRjjihKIwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATnfT1le+c1cjhY
pW/NxeFqQtuDnjnHWxXhjS3IF2/dLcVihC5UjKAT+JSLPK2PJaTJQH36eDey/ERR
7WcgSl/Fo4GKMIGHMA4GA1UdDwEB/wQEAwIHgDAdBgNVHSUEFjAUBggrBgEFBQcD
AQYIKwYBBQUHAwIwHQYDVR0OBBYEFBaMuseOOJ/iAhEQdkb1wEycTFijMB8GA1Ud
IwQYMBaAFA6U4Hd1RQp+nu9cF3MGwwlEQaJlMBYGA1UdEQQPMA2CC2V4YW1wbGUu
Y29tMAoGCCqGSM49BAMCA0gAMEUCIQDiagvyMRjblbQj2WF+jOyyxQF2PldIOFBm
rr9f1pn5fwIgApNUapu0bl/nTWrRrtrakDNjHTBtuGg7qgx5wLSlOjU=
-----END CERTIFICATE-----
```

Note that I had to use a SAN because a SAN must be encoded in IA5String and my subject cannot. But you can simply remove the SAN using a template. In any case in a template the proper value would be `"subject": {{ toJson .Insecure.CR.Subject }}`. And of course you can do the same using `step-ca` to create an intermediate with the proper path length:

A template like this should work:
```go
{
	"subject": {{ toJson .Insecure.CR.Subject }},
	"keyUsage": ["certSign", "crlSign"],
	"basicConstraints": {
		"isCA": true,
		"maxPathLen": 0
	}
}
```

**Comment by Drsmite** [comment]
The problem is, I believe, that the signed subject is not a bitwise match to the CSR subject.  This is being done with a JWK provisioner in step-ca.  I started looking through the code for where the subject is read from the CSR and /or where it is written out to find any encoding extension points.  So far I've been unsuccessful.

The difference when using the recommended template above and using the {{ toJson .Insecure.CR }} template is illustrated in the attachments.
When signed using the template you recommend, the consuming application throws an error about the encoding being wrong.
When signed with the insecure template, the subject encoding is accepted but the certificate isn't verifiable since the authority key remains unchanged and therefore looks self signed.

**Comment by maraino** [comment]
Oh, I see what you mean. The type of the ASN.1 object is PrintableString instead of UTF8String. Right now, you cannot use anything in the templates to convert a string that has only printable characters to UTF8. You can do that on extensions using functions like `asn1Enc' utf8:foo`, but not in the subject. In the subject it will only use UTF8String if it cannot be encoded using PrintableString.

However, I think we could extend the templates so you can copy the Raw version of the subject, something like:

```go
{
	"rawSubject": {{ .Insecure.CR.RawSubject | toJson }},
	"keyUsage": ["certSign", "crlSign"],
	"basicConstraints": {
		"isCA": true,
		"maxPathLen": 0
	}
}
```

This or something similar will copy the raw version of the subject to the final certificate. If you decide to use `rawSubject`, you won't be able to edit the subject easily. And `rawSubject` will always take priority over `subject`.

**Comment by maraino** [comment]
Hi @Drsmite, we will be releasing a new version this week, and you will be able to use a template like the one in my previous comment.
