### ISSUE TITLE
DirectoryUrl: "Not found"

### ISSUE THREAD

**Issue by aelmanaa** [smallstep/certificates#208]
Hello ,

probably there is something I'm not doing correctly but I've been stuck for the past few hours so I need some help.

just created a deployment via helm
`helm install stepcert smallstep/step-certificates --set ca.name=aem,ca.provisioner.name=aem,ca.provisioner.password=aem  -n test-devops`

then went inside the running pod to check that everything is working fine:

`kubectl exec -it -n test-devops stepcert-step-certificates-0 -- bash`

doing the following command works perfectly fine and I'm able to generate the certificate without any problem

`step certificate inspect --bundle srv.crt`

However, I'm trying to find what's the correct URL and I m going to expose it outside of k8s. hence I want to be able to know what's the URL of the directory. Problem is that when I'm a perform some curls in side the pod:

` curl https://stepcert-step-certificates.test-devops.svc.cluster.local/ --insecure
404 page not found`

or
`curl https://stepcert-step-certificates.test-devops.svc.cluster.local/acme/aem/directory --insecure
{"status":404,"message":"Not Found"}`

the health endpoint works though but any other endpoint returns 404. Also, when I perform "ca provisoner list" , I can see that the provisioner is "aem" .
`step ca provisioner list
[
   {
      "type": "jwk",
      "name": "aem",`

**Comment by dopey** [comment]
Hey @aelmanaa, apologies for the radio silence. We're usually better about helping with debugging from our [gitter](https://gitter.im/smallstep/community). That said we're a bit bogged down this week and early next week with a new release.

In the mean time, one thing that stands out is that you're trying to use an ACME provisioner with that url, but your CA is probably not configured with an ACME provisioner. Based on the helm deployment line, I'm guessing that you've got a JWK provisioner. So you would probably use the normal (non-acme api). A quick recommendation would be to use the `step cli`, if you can. It obfuscates the `step-ca` API which is nice, because the API is currently not documented in any useful way. 

Anyhow, hop in the gitter and we'll definitely try and help out over the next few days. Sorry again for the wait.

**Comment by dopey** [comment]
I'm going to close this issue, but if you're still trying to figure it out please re-open or hop on the gitter.
