### ISSUE TITLE
Support custom X.509 ExtraExtensions

### ISSUE THREAD

**Issue by lainosantos** [smallstep/certificates#275]
### What would you like to be added
Step ca support for teh user define custom x.509 extensions at certificate generation request.

### Why this is needed
That extensions may be used for several proposities, e.g. to store the user document number, the user birthday, and more relevant information for the user bussines.

**Comment by maraino** [comment]
@lainosantos: the extra extensions have to be present in the CSR, so I believe this issue will belong to smallstep/cli, right? 
Or do you want some fixed extensions for all certificates signed?

**Comment by lainosantos** [comment]
@maraino Thanks, you are right. extra extensions may be  present in the CSR.

However, fixed extensions for all certificates signed is a great feature too, is it already exists?

**Comment by maraino** [comment]
No, it's not something that we support in he CA at the moment. 

In the CLI we will add in the future the ability to configure custom extensions in the CSR, but we don't have a date yet.

**Comment by dopey** [comment]
We have an open issue for higher configurability of CSRs/Certificates in the cli (https://github.com/smallstep/cli/issues/110). 

I'm going to close this issue for the time being, because we don't have plans at the moment to add fixed extensions as part of authority or provisioner configuration. However, if you'd like to see those types of fixed extensions we can re-open the issue and maybe change the name to be more specific?
