### ISSUE TITLE
Re-keying for X509 certificates

### ISSUE THREAD

**Issue by dharanikumar-s** [smallstep/certificates#292]
### What would you like to be added
The existing renew feature for X509 certificate doesn't enable getting renewed certificate for new key pairs. The renew function should accept json data as http body. This json should contain a field for public key. If this field this present, existing renew function should provide a new certificate for this public key.

### Why this is needed
The end devices use certificates with longer period (ex. 1year). This period is defined by the lifetime of the private key, beyond which it is believed to be not secure. Hence certificate renewal includes change of key pair and obtaining renewed certificate for the new key pair.

### Why not short lived certificate
Below are my personal view. Please correct if this is wrong
The main reason behind short lived certificate is the failure of active revocation model among existing web servers and web browsers. But in my environment i am going to address this shortcoming by properly implementing OCSP.
In my environment i have thousand of devices handling critical functionality and they use certificates for identification. With short lived certificates, each devices need to contact CA to get their certificate renewed daily. If the CA is down, this will affect operation of the multitude of devices.

**Comment by mmalone** [comment]
Re-keying x.509 certificates is definitely a good idea. Honestly, I'm sort of embarrassed that we don't already support this. Keys are cheap, so reusing keys is of little value. Once this is implemented I think rekeying should be recommended for everyone, all the time, regardless of certificate lifetime, and the existing renew (which re-uses your existing key pair) should only be used if you have a good reason.

I think the implementation will be very similar to renew. We can base the API and CLI subcommand off of that code. I'd expect all of the same CLI flags to exist. As noted by @dharanikumar-s, the only real difference is that the new cert will bind a new public key instead of binding the old public key.

Some notes:

* Instead of sending the raw public key in the rekey request, we should probably send a certificate signing request (CSR) (like `step ca certificate` does). Since the CSR is self-signed, it adds an extra layer of data-origin authenticity, ensuring that the requestor does, indeed, have access to the associated private key.
* We need to consider race conditions when we write out the new certificate and private key. If the new cert is written to disk, followed by the new private key, software that uses the cert & key may try to load the cert & key in an inconsistent state with the new cert and old private key.

I'm not sure what the right answer is for the last point, but [this blog post on things UNIX can do atomically](https://rcrowley.org/2010/01/06/things-unix-can-do-atomically.html) is a good resource. This may be impossible or infeasible to work around without getting really clever, in which case the right answer might just be documentation.

**Comment by mmalone** [comment]
@dharanikumar-s this isn't _super_ relevant to the ticket, but I did want to respond with some thoughts about short-lived certificates vs OCSP... there certainly are use cases where OCSP (or CRL, or OCSP stapling) can make sense. I'm not sure whether you have one. My opinion (which I think is shared by most PKI experts) is that active revocation is fraught, for a bunch of reasons, and you should try really hard to make short-lived certificates and passive revocation work for you before resorting to active revocation.

> The main reason behind short lived certificate is the failure of active revocation model among existing web servers and web browsers.

Browers do support active revocation. But they're a bit of a moving target.

Some browsers support OCSP, but it introduces a privacy concern: the OCSP responder can tell which websites you're visiting based on the certificate status checks your browser makes. OCSP stapling helps here, and most browsers support stapling (although I think in some cases it's OS-dependent). I'm pretty sure every major web browser supports some form of active certificate revocation.

But it's not just browsers that are a problem here. Many TLS implementations don't do CRL or OCSP checks by default. If you have a very tightly controlled set of clients and servers you may be able to get away with CRL and/or OCSP, but you should be careful to check that they're doing what you expect and **don't assume that they will check revocation status out of the box.**

> If the CA is down, this will affect operation of the multitude of devices.

The same is true for OCSP (and CRL, and OCSP stapling).

CRLs are generally cached, which makes availability less of an issue, but also means that revocations don't happen immediately (you have to wait for caches to invalidate) so they lose any advantage over short-lived certs (just make your cert lifetimes equal to your CRL cache duration and you've accomplished the same thing).

With OCSP, an online request is made to your responder every time a certificate is validated. So if the responder goes down, you're toast. You do have the option of _failing open_ in this scenario: accepting a certificate as valid when your responder is down. But if you have a non-high-availability responder and a fail-open architecture you're not really adding much by doing OCSP checks since I can just DoS your responder and (mis)use your revoked certificates.

If you use OCSP stapling, you can take a bit of responder downtime without your whole system blowing up. So this helps a bit with resiliency. But, like CRLs+caching, it's basically equivalent to short-lived certs: if you're gonna staple a one-hour OCSP response to your certificates you might as well just issue one-hour certificates. You'll end up with essentially the same architecture from an availability perspective, but with less complexity.

Even if you do use active revocation it's a good idea to keep certificate lifetimes as short as possible. Your CRL/OCSP responder only needs to know about revoked certificates _that haven't expired_. So short certificate lifetimes keeps the active-set size of your revoked key database as small as possible.

So yea... it's complicated. There are a lot of reasons you might need or want active revocation, but it's not trivial, even when you can control the client & server. It definitely increases complexity and adds a bunch of new places where things can fail.

**Comment by dharanikumar-s** [comment]
Even with short lived certificates we can DoS the CA and disrupt the operation. So, Does HA is must for CA?

**Comment by mmalone** [comment]
@dharanikumar-s certainly CA availability is an issue for short-lived certificates. It’s probably the biggest issue, aside from simply arranging for all of the stuff that’s using certificates to properly rotate automatically (which you should be doing anyways, even with longer-loved certs).

Whether HA is a _must_ depends on your definition of HA. If you set things up properly you don’t need 100% CA uptime to keep your system running smoothly. By default, `step ca renew -daemon` will start trying to renew a cert when he’s 2/3 of the way through it’s lifetime. So, for a 24 hour lifetime, it’ll attempt renewal 8 hours before expiry. If renewal fails it’ll retry. So you could actually have up to 8 hours of CA downtime without impacting operations.

So your system will be HA even if your CA is not, so long as you can resolve any CA availability issues within 8 hours.
