### ISSUE TITLE
Making step-ca support fully-managed Cloud Run

### ISSUE THREAD

**Issue by mafrosis** [smallstep/certificates#308]
I did some work getting `step-ca` working on Cloud Run [here](https://github.com/mafrosis/certificates/tree/force-http) and [here](https://github.com/mafrosis/step-ca/tree/cloudrun).

Fully-managed Cloud Run insists on fronting your docker service with a Google certificate - even when using a custom domain. This subsequently causes `step ca *` to fail with `certificate signed by unknown authority` errors.

Can I run `step-ca` safely without mutual-TLS using the root CA cert? What are the implications?

Potentially this is just "it won't work" - but I would like to understand what options I have for "trusting" entities in this model if there is no mutual TLS between client and CA.

**Comment by dopey** [comment]
Here's a related issue: https://github.com/smallstep/certificates/issues/246 with a response from @mmalone on why http-only is not a short term priority. 

Most of the `step ca ...` subcommands do not require mTLS. I think the only one that does is `step ca renew`. So your command is failing the TLS because it cannot verify the certificate that is used to serve `step-ca`. As to whether we would ever turn off TLS - we'll track progress in the issue linked above. 

Our goal with `step-ca` was to make it easy to do TLS everywhere. Not requiring it in our CA is a bit of a contentious issue. It will involve a decent rework of the foundation of the codebase, which is why we haven't prioritized it short term.

**Comment by mafrosis** [comment]
Thanks @dopey. Happy to close this on favour of #246

**Comment by mmalone** [comment]
Fortuitously, we are currently working on a mechanism that may allow you to work around this issue. Check out https://github.com/smallstep/certificates/pull/531.

Long story short, we’re working on client-side support for a TLS-over-TLS tunnel. The outer layer of TLS can be terminated by any TLS-terminating TCP proxy. The inner layer is the normal TLS connection terminated by step-ca.

We’re building this to allow for an additional layer of security around a step-ca instance, as some folks don’t want to expose their CA to the public internet. I think it should work for this use case as well. Our current implementation expects to authenticate to the outer tunnel proxy using a client certificate, so we may need to make that optional (if it isn’t already). That should be a pretty minimal change. If it would allow step-ca to be run on FaaS platforms I think it’s worth doing.
