### ISSUE TITLE
bin dir mentioned in CentOS/RedHat install doesn't exist

### ISSUE THREAD

**Issue by youngd24** [smallstep/certificates#330]
The directory mentioned in the docs, bin, does not exist, seems to be cmd now.

sudo cp step_X.Y.Z/bin/step /usr/bin

Looks like it's sudo cp step_X.Y.Z/cmd/step now

Same for the server side I believe.

**Comment by maraino** [comment]
@youngd24 Can you send us the link of the tar file, because the ones I checked, the last releases for step and step-ca both have the bin directory

For [step-certificates_linux_0.14.6_amd64.tar.gz](https://github.com/smallstep/certificates/releases/download/v0.14.6/step-certificates_linux_0.14.6_amd64.tar.gz):
```sh
$ tar tzf step-certificates_linux_0.14.6_amd64.tar.gz
step-certificates_0.14.6/
step-certificates_0.14.6/README.md
step-certificates_0.14.6/bin/
step-certificates_0.14.6/bin/step-ca
step-certificates_0.14.6/bin/step-cloudkms-init
```

For [step_linux_0.14.6_amd64.tar.gz](https://github.com/smallstep/cli/releases/download/v0.14.6/step_linux_0.14.6_amd64.tar.gz):
```sh
$ tar tzf step_linux_0.14.6_amd64.tar.gz
step_0.14.6/
step_0.14.6/README.md
step_0.14.6/bin/
step_0.14.6/bin/step
```

**Comment by maraino** [comment]
Closing this issue as the binary releases have the bin directory
