### ISSUE TITLE
Azure AD and OIDC Provider

### ISSUE THREAD

**Issue by joshathysolate** [smallstep/certificates#339]
### Subject of the issue
It appears that the OIDC token / JWTs issued by Azure AD are consistently 5 minutes (ish) behind the actual time according to most NTP servers.  This causes *step ca certificate* to bomb out because it thinks the token was issued before the bootstrap of the CA.  (authority.Authorize: authority.authorizeSign: authority.authorizeToken: token issued before the bootstrap of certificate authority")

Also it appears that even though I have set "admins" and "domains" in my OIDC provisioner config, *step ca certificate* will not allow me to request a certificate with anything other than an email subject that matches the *email* field in the claim.  It's doing that validation before checking the actual provisioner config.  (or is this expected behavior??)

### Your environment
* OS - MacOS
* Version - 10.15.5 (Catalina)

### Steps to reproduce
Set up an Azure AD app:
`az ad app create --display-name "Your Application Name" --reply-urls http://127.0.0.1`

Add a new OIDC provisioner to the CA:
```
{
	"type": "OIDC",
	"name": "AzureAD Provisioner",
	"clientID": "CLIENT_ID",
	"clientSecret": "CLIENT_SECRET",
	"configurationEndpoint": "https://login.microsoftonline.com/TENANT/v2.0/.well-known/openid-configuration",
	"admins": [
		"john@smallstep.com"
	],
	"domains": [
		"smallstep.com"
	],
	"claims": {
		"maxTLSCertDuration": "8760h0m0s",
		"defaultTLSCertDuration": "168h0m0s"
	}
}
```

Try creating a new certificate for any hostname while logging into Azure AD as `john@smallstep.com`:
`./step ca certificate some.host.com server.crt server.key --san some.alternate.host.com --kty RSA --size 2048 --not-after 2020-12-31T23:59:59Z`

### Expected behaviour
I would expect the certificate to be issued by the CA assuming `john@smallstep.com` logs into Azure AD successfully.

### Actual behaviour
I get an error message:
`token email 'john@smallstep.com' and argument 'some.host.com' do not match`

After changing the command to use the email address as the subject:
`The request lacked necessary authorization to be completed. Please see the certificate authority logs for more info.`

And in the logs I see:
`error="authority.Authorize: authority.authorizeSign: authority.authorizeToken: token issued before the bootstrap of certificate authority"`

And I did verify the Azure AD token time is about 5 minutes before the start time, so this is more of an Azure AD timestamp problem.  I would say you should build in a 10 minute leeway or have that option at least to allow for a time discrepancy or the ability to disable this check.

When I finally bypassed the check by altering the code in `authority/authorize.go` and was able to get the certificate issued, the CN is set to some random set of characters and the email address is in the SAN.  I would expect the subject to be set to what was on the command line and the SAN to contain the subject/CN and the specified SANs.

I also bypassed the email check in the client in `command/ca/certificate.go` on lines 224-226 and used a hostname for the subject but that CN is not set (still some random string) and it does not even appear as a SAN. 

### Additional context
`./step ca certificate vpnproxy-01.us1.selab.hysolate.org server.crt server.key --san vpn.us1.internal.hysolate.org --kty RSA --size 2048 --not-after 2020-12-31T23:59:59Z`

...produces the following certificate...

```
-----BEGIN CERTIFICATE-----
MIIDYDCCAwWgAwIBAgIRAOI8lvenoC+U4pkCSUzMUMwwCgYIKoZIzj0EAwIwJDEi
MCAGA1UEAxMZSHlzb2xhdGUgTGFicyBJbnRlcm5hbCBDQTAeFw0yMDA4MDcwMzA3
MzlaFw0yMDEyMzEyMzU5NTlaMGYxFjAUBgNVBAoTDUh5c29sYXRlIEx0ZC4xFjAU
BgNVBAsTDUh5c29sYXRlIExhYnMxNDAyBgNVBAMTK01ZZS1URHVodDZ3ZmRuVjRR
cGRDUU10NHRXOWtrSUJZOGJ3cXFQY21rSlkwggEiMA0GCSqGSIb3DQEBAQUAA4IB
DwAwggEKAoIBAQC/4agEBVBbK9pHR5cHvNAVuwQE4B0l+CyLXsbNtiwJhqJBTXu9
wd6Oq40UcFzdTd145U71JJqLTYRadV8XApmF42ed2sXUrhriW+F1QgsR3QbtUr0r
kldv11m8aOIBRFs33XBVHL99iuQjo81EIVrVkB9M7zEELp7IVRp2P7aTPSmLH+6W
wcis2imZmf1XNDIdJnxHXmmVkUgvZKBy80fZMmfTo5kC1umwL7bWSkmgqPA60eRd
rqr55qEHGN8Eql6frOYUKd16iGMshfo1lzcwxBSHvR/AG0G64CVaAgBDlezrYhTT
vwWFIEmyfJbBo6n5sziqBbVXgWmrrVXQCip/AgMBAAGjggEJMIIBBTAOBgNVHQ8B
Af8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMB0GA1UdDgQW
BBTQDfhsaPVeDeA2L0P8zDO902yBaDAfBgNVHSMEGDAWgBQaqGb6vpgHHQFLDWLs
cosXmBJwXjA7BgNVHREENDAygh12cG4udXMxLmludGVybmFsLmh5c29sYXRlLm9y
Z4ERam9zaEBoeXNvbGF0ZS5jb20wVwYMKwYBBAGCpGTGKEABBEcwRQIBAgQaQXp1
cmVBRCAtIEh5c29sYXRlIExhYnMgQ0EEJGU5ZjBhMGUxLTgzN2YtNDkwNi05YzA0
LTEwYTA0M2JiNTRjZTAKBggqhkjOPQQDAgNJADBGAiEA45Nhanxnuo8sexNL1c+d
P4VawJj/LBAq72sheeugFUECIQD4ko98znmrSJuWNieQn0vf8nW265IfnWsKTNdp
dX0y4w==
-----END CERTIFICATE-----
```

**Comment by joshathysolate** [comment]
Okay I'm seeing that the CN is coming directly from the "Subject" in the JWT payload and this is getting set in the cli project in `utils/cautils/certificate_flow.go` on lines 275-279.  To me this doesn't make sense to assign the subject from the JWT payload to create the CSR when I'm specifying a subject on the command-line.

**Comment by maraino** [comment]
> It appears that the OIDC token / JWTs issued by Azure AD are consistently 5 minutes (ish) behind the actual time according to most NTP servers. This causes step ca certificate to bomb out because it thinks the token was issued before the bootstrap of the CA. (authority.Authorize: authority.authorizeSign: authority.authorizeToken: token issued before the bootstrap of certificate authority")

This is a feature that we added way back before having a DB, when all the tokens were stored in memory. You can still run some provisioners like this, so this is the default behavior. But you can change this adding to the ca.json `"disableIssuedAtCheck": true` under `"authority"`:
```js
{
    "root": "...",
    ...
    "authority": {
       "disableIssuedAtCheck": true,
       "provisioners: {...}
    }
}
```

> Also it appears that even though I have set "admins" and "domains" in my OIDC provisioner config, step ca certificate will not allow me to request a certificate with anything other than an email subject that matches the email field in the claim. It's doing that validation before checking the actual provisioner config. (or is this expected behavior??)

As an admin, the CA bypasses some of the checks that the OIDC provisioner does, like enforcing the email to be your only SAN. But it seems that the `step` cli is the one enforcing you run something like:
```
step ca certificate --san example.org john@doe.com example.crt example.key
```
instead of just
```
step ca certificate example.org example.crt example.key
```

There is currently a couple of ways to "bypass" this. The first one would be to use `step ca sign` instead of `step ca certificate`. But the CLI still will check that the subject (`"sub"`) of the token matches the certificate common name in the subject. Not ideal but it might work. So the process would be like this:

```
step certificate create --csr --san example.org the-token-subject example.csr example.key
step ca sign example.csr example.crt
```

The second option would be to run curl and send the CSR that you want with the token. The CA is not checking the CSR if you are an admin. Of course, this is not straightforward.

The CLI shouldn't be that strict, so this part can be considered an issue.

-- 

For machine certificates, we always recommend a different type of provisioner, JWK (the more flexible, and my personal preference) or the instance identity document ones (AWS, Azure, GCP), but these are a little bit more strict.

In the next release, we're introducing certificate-flexibility, especially in the CA area. With this, you will be able to create custom templates for each provisioner,  and you will be able to use your CSR and unverified arguments from the CLI to build your custom certificate. Right now, there are some branches that we're working on with this functionality:
* cli: https://github.com/smallstep/cli/tree/cert-flexibility
* certificates: https://github.com/smallstep/certificates/tree/cert-templates and https://github.com/smallstep/certificates/tree/ssh-cert-templates

**Comment by dopey** [comment]
Hey @joshathysolate, I'm going to close this issue as I think #340 covers the scope of any additional functionality that may be required. But feel free to re-open if you'd like to discuss further, or if you think there are more issues to keep track of.

**Comment by nodakai** [comment]
I had to enable `disableIssuedAtCheck` for my Azure AD free. Maybe you can apply `backdate` mechanism to `issuedAt` check as well?

**Comment by wrongecho** [comment]
Super old thread but felt the necrobump might be helpful. 

I just wanted to note that I was also (intermittently) running into this issue with Azure.
Disabling the issued at check also prevented the errors for me.
