### ISSUE TITLE
Lifespan Jitter

### ISSUE THREAD

**Issue by jcpunk** [smallstep/certificates#350]
### What would you like to be added

I would like to add a small (but semi-random) extra lifespan to issued certificates.

### Why this is needed

When running at scale, if I use the remaining certificate lifetime as a trigger (renew cert if lifetime <= X) hosts can begin to lump together around specific times.

Adding, for example, up to 20 minutes of extra life (at psudo-random) will allow the clients to slowly drift apart (using the standard cronjob from `certbot.sh`).  Over the course of a few weeks clients that got a few seconds and clients that got 20 minutes will begin to drift apart and limit load spikes on the certificate server.

**Comment by maraino** [comment]
@jcpunk I'm leaving this here for triage by the team. But I think the same can be applied to `certbot.sh`, for example when our servers renew their certificates, they apply a random jitter https://github.com/smallstep/certificates/blob/5d17c8b011bae14f24245ddb8c33502e7d216aa2/ca/renew.go#L183-L191

**Comment by mmalone** [comment]
Just here to reiterate that:

1. I'm not wholly opposed to adding some jitter to certificate lifetimes, but
2. I do think renewal logic is a better place to solve this

I'll add a bit of context and justification. First, most mature certificate management tools already do this on renewal (e.g., `step` does and I'm pretty sure `certbot` does too). Furthermore, it'd be pretty easy for a naive renewal job to screw things up even _with_ this jitter (e.g., a 20 minute jitter won't help you if all of your `cron` jobs are scheduled to run and renew at midnight the night before expiry). So a naive renewal job is gonna mess things up either way.

In fact, I'm pretty sure I ran into an issue with `certbot` for super short-lived ACME certs because of this. I think they add a fixed-size jitter (e.g., +/- 20 min) which can cause problems for extremely short-lived certs. For this reason I'd suggest using a percentage-based jitter. Something like "renew after 2/3 of lifetime +/- 5%".

One final note: the CA has pretty solid performance. The most expensive part of issuing a certificate is signing, so this varies based on signature algorithm and key type, but you'd have to have a pretty large infrastructure to generate a thundering herd that's big enough to pin the CA. That said, looking at your GitHub bio, maybe you do... :)

**Comment by dopey** [comment]
Hey @jcpunk let us know if the previous response (basically letting the `renew` operator handle jitter) makes sense. Unless there's more discussion or increased interest from the community for this feature we'll go ahead and close the issue as "won't fix".

**Comment by jcpunk** [comment]
Works for me, feel free to close out 'Won't Fix'
