### ISSUE TITLE
Compatibility with CSRs that have no SANs.

### ISSUE THREAD

**Issue by dopey** [smallstep/certificates#45]
### Compatibility with CSRs that have no SANs.
Currently `step` enforces SAN compatibility in a number of different places in cli and certificates which makes thinking about and changing the codebase difficult.

`step cli` - All tokens not generated directly from a CSR will have a default SAN (the subject common name) if the SANs have been left empty.
`step certificates` - If the token has no SANs then the subject of the of the CSR will be added to the token as a SAN. This was originally added for backwards compatibility b/c certs generated by `step cli` always added the common name as a SAN, while the tokens did not.

This logic is confusing and does not work correctly in the case where a CSR with no SANs is passed to `step ca sign`. The token will be created by `step cli` correctly (w/out additional SANs), but `step certificates` will add a SAN to the token which will break authentication.

**Comment by maraino** [comment]
`step certificate create --csr` already adds a san by default, exactly like `step ca certificate` does (if there're no sans passed using the `--san` flag).
For the case of a csr with no sans, instead of implementing a new flag `--no-san` we'll wait to support this using the json templates to generate csrs.
