### ISSUE TITLE
Remove requirement for OIDC well-known endpoint to have jwks_uri set

### ISSUE THREAD

**Issue by techknowlogick** [smallstep/certificates#577]
### What would you like to be added
Per https://github.com/smallstep/certificates/blob/5a6517ca5b963e09e5d9cc66b66521cc71c6483e/authority/provisioner/oidc.go#L34 and https://github.com/smallstep/certificates/blob/5a6517ca5b963e09e5d9cc66b66521cc71c6483e/authority/provisioner/oidc.go#L195 a jwks_uri needs to be provided.

### Why this is needed
Current OIDC provider does not provide jwks_uri in OIDC well-known endpoint, and only supports `HS256` (can't be switched to `RS256` either). 

The well-known endpoint from oidc provider returns:
```
{
    "issuer": "https://example.com/",
    "authorization_endpoint": "https://example.com/login/oauth/authorize",
    "token_endpoint": "https://example.com/login/oauth/access_token",
    "response_types_supported": [
        "code",
        "id_token"
    ]
}
```

PS, ❤️ Thanks for Smallstep suite of OSS that you publish.

**Comment by mmalone** [comment]
Hi @techknowlogick,

Unfortunately, I don't think this is something we can easily support.

The OIDC standard specifies two ways to sign identity token JWTs:

  1. Using asymmetric cryptography (public/private keys), in which case the public keys for verifying the JWTs are obtained by dereferencing the `jwks_uri` obtained from the OIDC well-known endpoint. This is what we use, and the `jwks_uri` is required.
  2. Using symmetric cryptography (a shared secret), in which case the JWT is signed (and verified) using the OAuth client secret.

We use an OAuth native flow (see [BCP212](https://datatracker.ietf.org/doc/html/rfc8252)) with a "public client", which means we can't keep the "client secret" secret. In this configuration, symmetric signing of identity tokens would not be secure (anyone would be able to forge a token). If you look at section 10.2 of the [OIDC spec](https://openid.net/specs/openid-connect-core-1_0.html) it says "symmetric encryption MUST NOT be used by public (non-confidential) Clients because of their inability to keep secrets."

In order to support this, we'd need to support a different OAuth flow that's able to maintain client secret confidentiality. That'd probably mean redirecting the OAuth client back to the CA instead of to the client. That'd be a pretty major change.

I'm curious: what identity provider (IdP) are you using? I've never seen an IdP that uses symmetric cryptography for identity tokens.

**Comment by dopey** [comment]
This would only be possible if we add a OAuth redirect to `step-ca`. That's not currently on our roadmap.
