### ISSUE TITLE
I can't find the way to validate the chain of certificates

### ISSUE THREAD

**Issue by kirill-kostenetskyi** [smallstep/certificates#637]
Hi there!
Our product needs certificates issued as a four-level chain and we chose step-ca as CA which seems should do the job for us. 
We have not a lot of experience in the certification area, just a basic understanding. Let me know if we understand something in the wrong way, please.
We setup `step-ca` server and then we use this sort of commands to create the chain: 
1. `step ca certificate --ca-url https://33.333.333.333:443 account account.crt account.key` 
using JWK provider
2. Then we use `x5c` provisioner to create the new certificate based on the previous:
 `step ca certificate --ca-url https://33.333.333.333:443 session account_2.crt account_2.key --provisioner=x5c@dev --x5c-cert=account.crt --x5c-key=account.key`
3. Then we use `x5c` provisioner again to create the next certificate level:
`step ca certificate --ca-url https://33.333.333.333:443 session account_3.crt account_3.key --provisioner=x5c@prod --x5c-cert=account_2.crt --x5c-key=account_2.key`

So after that, we have at least three certificates (and another two inside `step-ca` server). Here are the questions:
1. How can we validate that `account_3.crt` was issued by `account_2.crt` or `account_2.crt`  was issued by `account.crt` ? Does step has any functions to do that? 
2. Does it store them and keeps records?
3. Does `step` the good choice for our purposes? 

Could somebody please help us with answers?

**Comment by dopey** [comment]
Hey @kirill-kostenetskyi, glad you're trying out step for this. I think there's a  couple misunderstandings about how the CA works and how certificates are signed, so let me try to clear those up.

When `step ca init` is run you get a root and intermediate certificate. When you start up `step-ca` every new certificate that is signed is signed by that intermediate certificate. Run `step certificate inspect` against any of your account_2.crt or account_3.crt and you'll see that they're signed by the intermediate, not another downstream cert.

A provisioner is a way to authenticate to the authority, rather than a way to select the signing CA. So when you use a JWK provisioner you authenticate via password. When you use a X5c certificate you authenticate via an x509 certificate previously issued by the CA. But each of the new certificates that you generate will be signed by the original intermediate.

Now, you say that for your product you need a chain that is 4 certificates long. This possible with `step-ca` but it’s not the default behavior. What you'll want to do is generate a root certificate using the `step` cli. By default, the root certificate generated by `step ca init` generates a root certificate with a max pathlen of `1`, meaning that there can only be one intermediate certificate in the chain (between root and leaf). You will want a pathlen of `2`. Here's an example template you could use: 

```
{
    "subject": {{ toJson .Subject }},
    "issuer": {{ toJson .Subject }},
    "keyUsage": ["certSign", "crlSign"],
    "basicConstraints": {
        "isCA": true,
        "maxPathLen": 2
    }
}
```

Using this template you would run `step certificate create --template root.tpl root_ca my-new-root-subject root.crt root.key`.
Then you would create your first intermediate. By default the intermediate created by `step ca init` has a pathlen of 0 (does not allow any more intermediates in the chain), so you'll need to create one yourself using a new template.

Here's an example: 
```
// intermediate1.tpl
{
    "subject": {{ toJson .Subject }},
    "keyUsage": ["certSign", "crlSign"],
    "basicConstraints": {
        "isCA": true,
        "maxPathLen": 1
    }
}

step certificate create --template intermediate1.tpl --ca root.crt --ca-key root.key <subject> intermediate1.crt intermediate2.crt
```

Next you'll want to create your second intermediate:

```
step certificate create --profile intermediate_ca --ca intermediate1.crt --ca-key intermediate1.key <subject> intermediate2.crt intermediate2.key
```

Next, bundle intermediate 1 and 2 into a single file, with 2 being on top of 1:

```
step certificate bundle intermediate2.crt intermediate1.crt intermediate_bundle.crt

Finally, you'll need to update your `ca.json`:

```
{
	"root": "<location of root.crt>",
	"crt": "<location of intermediate_bundle.crt>",
	"key": "<location of intermediate2.key>",
}

Now, start up step-ca and when you create certificate using any provisioner they will be signed by intermediate2 and you will have a path length of 4 certificates.
