### ISSUE TITLE
Acme.sh can't register account and getting "Account does not exist"

### ISSUE THREAD

**Issue by jc21** [smallstep/certificates#749]
### Subject of the issue

I'm using [my own step-ca docker server](https://github.com/NginxProxyManager/docker-testca) and trying to either create an account or request a cert using acme.sh client.

The logs response reported by acme.sh is:

```
response='{"type":"urn:ietf:params:acme:error:accountDoesNotExist","detail":"Account does not exist"}'
```
whereas the step-ca logs for the error is actually:
```
time="2021-11-17T13:39:48Z" level=warning duration="53.975µs" duration-ns=53975 error="provisioner must be of type ACME" fields.time="2021-11-17T13:39:48Z" method=GET name=ca path=/acme/nginxproxymanager/directory protocol=HTTP/2.0 referer= remote-address=192.192.192.10 request-id=c6agc954t7h7dekcsqs0 size=92 status=400 user-agent="acme.sh/3.0.2 (https://github.com/acmesh-official/acme.sh)" user-id=
```

### Your environment
* OS - Centos
* Version - 8
* Acme.sh - 3.0.2
* Smallstep CA - 0.17.6

### Steps to reproduce

1. Run the testca docker image:
```bash
docker run --name testca --rm -d --add-host "ca.internal:127.0.0.1" nginxproxymanager/testca
```
2. Attempt to register an account:
```bash
docker exec -ti testca ./acme.sh \
  --register-account \
  --server https://ca.internal/acme/nginxproxymanager/directory \
  --ca-bundle /home/step/certs/root_ca.crt \
  -m jc@jc21.com \
  --debug 2
```
3. View docker logs:
```bash
docker logs testca
```
4. Stop container when done
```
docker stop testca
```

### Expected behaviour

A successful response from the step-ca server

### Actual behaviour

acme.sh command reports:
```
response='{"type":"urn:ietf:params:acme:error:accountDoesNotExist","detail":"Account does not exist"}'
```

step-ca reports:
```
provisioner must be of type ACME
```

### Additional context

Could this somehow be something to do with the way the step-ca server is setup? I used [this article](https://smallstep.com/blog/private-acme-server/) as a starting point for this setup.

At any rate, the mismatching error messages is concerning.

EDIT: correct docker network string

**Comment by dopey** [comment]
Hey @jc21 thanks for opening up the issue. 

So, my guess is that you are missing an ACME provisioner in your configuration. I'll want to see your `$(step path)/config/ca.json` to confirm. In the blog post that you refer to, there is a step for adding an ACME provisioner. 

Since you're using the Docker image you'll likely need to overwrite the default ca.json in the container. What you want to do is add the following object to the provisioners struct in the `ca.json`: 

```
{
    "name": "acme",
    "type": "ACME",
}. 
```
When you restart the CA the acme provisioner and API will be available. I think the `ca-url` will be `ca.internal/acme/acme/directory`.

Now, with regards to the error. I believe your ACME client is showing that error because the CA is responding 404 (the path is not found because the API was not initialized because there are no ACME provisioners configured) and the ACME client assumes that the 404 is about the missing account. That's my best guess.

Let me know if you have questions about how to configure your CA for ACME use. There should be some examples of the configuration required in the blog post you linked.

**Comment by jc21** [comment]
Thanks @dopey this was helpful.

The [step/config/ca.json](https://github.com/NginxProxyManager/docker-testca/blob/master/step/config/ca.json) did have the acme provisioner, but I was accessing it on the wrong path.

The error was not coming from the Acme client though, and seems to be specific to the setup I have:
```bash
# curl --insecure https://ca.internal/acme/anything/directory
{"type":"notFound","detail":"resource not found","message":"provisioner anything not found"}

# curl --insecure https://ca.internal/acme/nginxproxymanager/directory
{"type":"urn:ietf:params:acme:error:accountDoesNotExist","detail":"Account does not exist"}

# curl --insecure https://ca.internal/acme/acme/directory
{"newNonce":"https://ca.internal/acme/acme/new-nonce","newAccount":"https://ca.internal/acme/acme/new-account","newOrder":"https://ca.internal/acme/acme/new-order","revokeCert":"https://ca.internal/acme/acme/revoke-cert","keyChange":"https://ca.internal/acme/acme/key-change"}
```

I've tested using that last path with acme.sh and it's working as expected :)
