### ISSUE TITLE
Using smallstep as an intermediate CA with certificates provided by a parent CA

### ISSUE THREAD

**Issue by Montana** [smallstep/certificates#803]
I saw a similar thread, but I'll type out my unique (to me) issue. 

I am looking to use an intermediate CA which can sign certificates via ACME, I do not want to use Venafi, or any other service other than **smallstep.** We have a number of internal web servers (mostly running Django) which are not accessible on the internet which use SSL/SSH all of which need to be managed manually from a Gentoo box. 

We already have an internal CA where the CA authority is installed on all internal machines. I was hoping to install smallstep, with a certificate provided from the existing authority which it can then use to sign certificates using ACME (all of the servers are in DNS and this DNS is managed internally, so a DNS name check is a valid check).

If I wanted to do this, in theory, I'd configure all of your ACME clients to trust the root that `step-ca` generates when you run `step ca init`, and/or:

```bash
step ca init --root=[ROOT_CERT_FILE] --key=[ROOT_PRIVATE_KEY_FILE]
```
Then (if need be, I can remove the intermediate key?). So this meaning I'd want to plausibly replace the intermediate `.crt` and signing key produced by `step ca init` with the new ones, if we switch over fully. 

Some of this information is in the documentation, but it's a bit opaque. I appreciate any help. Thanks @mmalone, for making an awesome product my friend! 

Cheers,
Montana Mendy

**Comment by hslatman** [comment]
Hi @Montana,

If I understand you correctly, you'd like to run an ACME CA that signs certificates for which the root CA trust anchor has already been distributed? Because in that case, `step ca init --root=[ROOT_CERT_FILE] --key=[ROOT_PRIVATE_KEY_FILE]` will indeed do what you want: it creates a new intermediate CA certificate signed by the issuer in the root certificate. `step-ca` will then use that intermediate to sign certificate requests.

Please note that this action requires access to the root key of your existing internal CA when initializing. `step-ca` needs the root certificate configured and will copy that in the process. The private key is not required for `step-ca` to operate, so that can be removed, if it was copied over to the location of the `step-ca` configuration (i.e. `$STEPPATH`). You'll not want to remove the intermediate key, as it's required to sign certificate requests. You can protect it with a password or a password file. It's also possible to store the key in a KMS or HSM, if your use case requires that.

The above is just one way for making `step-ca` work with an existing trust anchor. In general `step-ca` can work with an existing root certificate and an intermediate cert/key pair signed by that root, as long as these are configured and can be read.

Let me know if this answers your question or if I misunderstood.

**Comment by Montana** [comment]
Hey @hslatman,

This is what I was looking for, specifically the **trust anchor** bit. I think what I can do is run:

```bash
cat $(step path --base)/current-context.json
step path --base
```
From what I've read here and get the results I want.  I really appreciate it.

**Comment by Montana** [comment]
Another useful point, thanks so much @hslatman!
