### ISSUE TITLE
Add additional key algorithms to step-pkcs11-init

### ISSUE THREAD

**Issue by mikansontap123** [smallstep/certificates#925]
### What would you like to be added
Currently `step-pkcs11-init` appears to be locked to ECDSA P-256. In some scenarios, the ability to choose P-384 might be more appropriate. Similarly RSA keys may be required for other applications.

### Why this is needed
To fulfill compliance and compatibility needs of various PKI implementations.

**Comment by tashian** [comment]
Hi @mikansontap123,

For now, you can build a version of `step-pkcs11-init` for this.

For example, for P-384, change [this file](https://github.com/smallstep/certificates/blob/master/cmd/step-pkcs11-init/main.go) to use 384 bits instead of 256 on lines [297](https://github.com/smallstep/certificates/blob/af17b6a6f3d8f0d5df8f16a08a7d643308483a60/cmd/step-pkcs11-init/main.go#L297), [401](https://github.com/smallstep/certificates/blob/af17b6a6f3d8f0d5df8f16a08a7d643308483a60/cmd/step-pkcs11-init/main.go#L401), and [463](https://github.com/smallstep/certificates/blob/af17b6a6f3d8f0d5df8f16a08a7d643308483a60/cmd/step-pkcs11-init/main.go).

Hope this helps.

**Comment by mikansontap123** [comment]
@tashian 
Thank you, gave it a try on a test instance and seems to work just fine!
