### ISSUE TITLE
[Bug]: TTY required even if all parameters are passed to `step ca init`

### ISSUE THREAD

**Issue by tacerus** [smallstep/certificates#949]
### Steps to Reproduce

1. Establish terminal session without tty allocation - for testing, a simple call using `ssh -T` can be used
2. ` /usr/bin/step ca init --deployment-type=standalone --name=foo-ca --dns=foo.example.com --address=[::1]:443 --provisioner=foo-ca --password-file=/etc/step-ca/pass.txt --provisioner-password-file=/etc/step-ca/pass.txt --with-ca-url=https://foo.example.com`

### Your Environment

* OS - SUSE Linux Enterprise Server 15 SP3
* `step-ca` Version - Smallstep CA/0.20.0

### Expected Behavior

1. The CA should be initialized
2. No error messages should be printed
3. `0` should be returned

### Actual Behavior

The CA initializes partially, afterwards the command fails:

`error allocating terminal: open /dev/tty: no such device or address`

### Additional Context

Hi,

by default, `step ca init` asks the user for required values interactively, and naturally requires a terminal to do so.

However, if all required parameters are passed on the [command line](https://smallstep.com/docs/step-cli/reference/ca/init), this should not be required.

Currently, the following fails in an automated environment without pseudo-tty allocation:

```
$ /usr/bin/step ca init --deployment-type=standalone --name=foo-ca --dns=foo.example.com --address=[::1]:443 --provisioner=foo-ca --password-file=/etc/step-ca/pass.txt --provisioner-password-file=/etc/step-ca/pass.txt --with-ca-url=https://foo.example.com

                  Generating root certificate... done!
                  Generating intermediate certificate... done!
                  error allocating terminal: open /dev/tty: no such device or address
```

Is there possible a parameter which I missed?
If not, it would be nice if this could be taken up as a feature request, to ease the deployment with management systems like Salt.

Best,
Georg

**Comment by hslatman** [comment]
Hi @tacerus,

We're aware there are certain code paths in which `step` prompts for user input, even though they are specified on the CLI. We have somes issues open for it in the CLI repo here: https://github.com/smallstep/cli/issues/674 and a more generic one here: https://github.com/smallstep/cli/issues/502. That's probably also where this issue has to go, since it's about the `step` CLI. Some known cases are wrong inputs (e.g. ones that are empty after shell substitution) and when errors are encountered somewhere in the process that currently only support interactive fixing (e.g. files already existing and prompting to overwrite them). 

I noticed you're using `[::1]:443` as the address. I vaguely remember having issues with that on the CLI when the brackets were not escaped, but I may be wrong. You could try `--address="[::1]:443"` instead to see if that works, but I'm not entirely sure. I also tried to reproduce this error; the first time it was successful, but the second time it prompted me to overwrite the root and intermediate files. Is it possible the files already exist in your environment?

**Comment by tacerus** [comment]
Hi @hslatman, thank you, and apologies for missing these existing issues upon searching through the open ones - #674 indeed seems similar, but I do not fully agree with #502, as in my opinion, a flag such as `--non-interactive`, as suggested by the reporter, should be assumed by default if all necessary values have been passed through command line arguments.

The address I think is fine - because if I run the same exact command snippet with an interactive terminal, it executes just fine. Sorry to ask, but did you actually attempt it in an environment without a tty?

**Comment by tacerus** [comment]
Ah! Now I got what you mean.

I was able to reproduce your scenario, with it trying to ask if existing files should be overridden. With a manual attempt through `ssh` it now works fine if I clean up all previous files beforehand, thank you! Not so with my automated script (Salt) however, where it still complains with `error allocating terminal`, even if I take care of removing all files beforehand - possibly something is different in the automated environment, and the terminal error causes it to not print the exact reason.

Since the existing issues you referred are similar, do you still want to keep this one?

**Comment by hslatman** [comment]
Bummer 😞 Is it storing the files in the location you're expecting or maybe a different one (based on the user account it's running as)? And I assume the password files exist and can be found too by the user? Running it with `STEPDEBUG=1` may give a bit more information; it should at least give the call stack, which should make it easier to pinpoint.

Let's keep it open for a bit and see if we can resolve your specific case. I think cleaning up in your own scripts (without a `--force` option) is probably the safest thing to do, since you have to be intentional about overwriting the root and intermediate.

**Comment by tacerus** [comment]
Thanks for the tip with `STEPDEBUG`! I added it to the environment variables and captured stdin and stderr:

<details>
<summary>Output</summary>

```
Generating root certificate... done!
Generating intermediate certificate... done!
open /dev/tty: no such device or address
error allocating terminal
go.step.sm/cli-utils/ui.preparePromptTerminal
        /home/abuild/rpmbuild/BUILD/cli-0.20.0/vendor/go.step.sm/cli-utils/ui/ui.go:281
go.step.sm/cli-utils/ui.Prompt
        /home/abuild/rpmbuild/BUILD/cli-0.20.0/vendor/go.step.sm/cli-utils/ui/ui.go:156
go.step.sm/cli-utils/fileutil.WriteFile
        /home/abuild/rpmbuild/BUILD/cli-0.20.0/vendor/go.step.sm/cli-utils/fileutil/write.go:54
github.com/smallstep/certificates/pki.(*PKI).WriteFiles
        /home/abuild/rpmbuild/BUILD/cli-0.20.0/vendor/github.com/smallstep/certificates/pki/pki.go:714
github.com/smallstep/certificates/pki.(*PKI).Save
        /home/abuild/rpmbuild/BUILD/cli-0.20.0/vendor/github.com/smallstep/certificates/pki/pki.go:926
github.com/smallstep/cli/command/ca.initAction
        /home/abuild/rpmbuild/BUILD/cli-0.20.0/command/ca/init.go:631
github.com/urfave/cli.HandleAction
        /home/abuild/rpmbuild/BUILD/cli-0.20.0/vendor/github.com/urfave/cli/app.go:522
github.com/urfave/cli.Command.Run
        /home/abuild/rpmbuild/BUILD/cli-0.20.0/vendor/github.com/urfave/cli/command.go:173
github.com/urfave/cli.(*App).RunAsSubcommand
        /home/abuild/rpmbuild/BUILD/cli-0.20.0/vendor/github.com/urfave/cli/app.go:405
github.com/urfave/cli.Command.startApp
        /home/abuild/rpmbuild/BUILD/cli-0.20.0/vendor/github.com/urfave/cli/command.go:372
github.com/urfave/cli.Command.Run
        /home/abuild/rpmbuild/BUILD/cli-0.20.0/vendor/github.com/urfave/cli/command.go:102
github.com/urfave/cli.(*App).Run
        /home/abuild/rpmbuild/BUILD/cli-0.20.0/vendor/github.com/urfave/cli/app.go:277
main.main
        /home/abuild/rpmbuild/BUILD/cli-0.20.0/cmd/step/main.go:113
runtime.main
        /usr/lib64/go/1.18/src/runtime/proc.go:250
runtime.goexit
        /usr/lib64/go/1.18/src/runtime/asm_amd64.s:1571
```

</details>

Unfortunately, I cannot quite make sense of it myself :-( Any chance you can deduct from this what it needs?

**Comment by tacerus** [comment]
>  Is it storing the files in the location you're expecting or maybe a different one

I use `STEPPATH: '/var/lib/step-ca'` which it seems to be respecting.

**Comment by hslatman** [comment]
@tacerus: great to hear you sorted it out! Wanted to get back to you before, but something else popped up.

Your solution checks out with the debug call stack, too: it failed on the file already existing. 

I think that a generic solution for cases where a tty is not available is to 1) write a descriptive error to `stderr` and 2) exit with an error code.
